namespace UI
{
    partial class FormGestionSalon
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionSalon));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.PanelData = new System.Windows.Forms.Panel();
            this.LblErrorCantidadMinimaInvitados = new Bunifu.UI.WinForms.BunifuLabel();
            this.NumCantidadMinimaInvitados = new System.Windows.Forms.NumericUpDown();
            this.NumCapacidad = new System.Windows.Forms.NumericUpDown();
            this.TxtPrecioCubierto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorPrecio = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtPrecio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorCapacidad = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorUbicacion = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorPrecioCubierto = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorNombre = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtUbicacion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnModificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCrear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DataGridViewSalones = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.PanelData.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.NumCantidadMinimaInvitados)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.NumCapacidad)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewSalones)).BeginInit();
            this.SuspendLayout();
            // 
            // PanelData
            // 
            this.PanelData.Controls.Add(this.LblErrorCantidadMinimaInvitados);
            this.PanelData.Controls.Add(this.NumCantidadMinimaInvitados);
            this.PanelData.Controls.Add(this.NumCapacidad);
            this.PanelData.Controls.Add(this.TxtPrecioCubierto);
            this.PanelData.Controls.Add(this.bunifuLabel8);
            this.PanelData.Controls.Add(this.LblErrorPrecio);
            this.PanelData.Controls.Add(this.TxtPrecio);
            this.PanelData.Controls.Add(this.bunifuLabel6);
            this.PanelData.Controls.Add(this.LblErrorCapacidad);
            this.PanelData.Controls.Add(this.LblErrorUbicacion);
            this.PanelData.Controls.Add(this.LblErrorPrecioCubierto);
            this.PanelData.Controls.Add(this.LblErrorNombre);
            this.PanelData.Controls.Add(this.BtnCancelar);
            this.PanelData.Controls.Add(this.BtnGuardar);
            this.PanelData.Controls.Add(this.bunifuLabel2);
            this.PanelData.Controls.Add(this.TxtNombre);
            this.PanelData.Controls.Add(this.TxtUbicacion);
            this.PanelData.Controls.Add(this.bunifuLabel5);
            this.PanelData.Controls.Add(this.bunifuLabel4);
            this.PanelData.Controls.Add(this.bunifuLabel3);
            this.PanelData.Location = new System.Drawing.Point(3, 300);
            this.PanelData.Name = "PanelData";
            this.PanelData.Size = new System.Drawing.Size(897, 280);
            this.PanelData.TabIndex = 30;
            // 
            // LblErrorCantidadMinimaInvitados
            // 
            this.LblErrorCantidadMinimaInvitados.AllowParentOverrides = false;
            this.LblErrorCantidadMinimaInvitados.AutoEllipsis = false;
            this.LblErrorCantidadMinimaInvitados.CursorType = null;
            this.LblErrorCantidadMinimaInvitados.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorCantidadMinimaInvitados.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorCantidadMinimaInvitados.Location = new System.Drawing.Point(422, 246);
            this.LblErrorCantidadMinimaInvitados.Name = "LblErrorCantidadMinimaInvitados";
            this.LblErrorCantidadMinimaInvitados.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorCantidadMinimaInvitados.Size = new System.Drawing.Size(216, 15);
            this.LblErrorCantidadMinimaInvitados.TabIndex = 34;
            this.LblErrorCantidadMinimaInvitados.Text = "Debe ingresar cantidad minima invitados";
            this.LblErrorCantidadMinimaInvitados.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorCantidadMinimaInvitados.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorCantidadMinimaInvitados.Visible = false;
            // 
            // NumCantidadMinimaInvitados
            // 
            this.NumCantidadMinimaInvitados.Location = new System.Drawing.Point(422, 220);
            this.NumCantidadMinimaInvitados.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this.NumCantidadMinimaInvitados.Name = "NumCantidadMinimaInvitados";
            this.NumCantidadMinimaInvitados.Size = new System.Drawing.Size(135, 20);
            this.NumCantidadMinimaInvitados.TabIndex = 33;
            // 
            // NumCapacidad
            // 
            this.NumCapacidad.Location = new System.Drawing.Point(10, 220);
            this.NumCapacidad.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this.NumCapacidad.Name = "NumCapacidad";
            this.NumCapacidad.Size = new System.Drawing.Size(135, 20);
            this.NumCapacidad.TabIndex = 32;
            // 
            // TxtPrecioCubierto
            // 
            this.TxtPrecioCubierto.AcceptsReturn = false;
            this.TxtPrecioCubierto.AcceptsTab = false;
            this.TxtPrecioCubierto.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.TxtPrecioCubierto.AnimationSpeed = 200;
            this.TxtPrecioCubierto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPrecioCubierto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPrecioCubierto.AutoSize = true;
            this.TxtPrecioCubierto.BackColor = System.Drawing.Color.Transparent;
            this.TxtPrecioCubierto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPrecioCubierto.BackgroundImage")));
            this.TxtPrecioCubierto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPrecioCubierto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPrecioCubierto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPrecioCubierto.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPrecioCubierto.BorderRadius = 1;
            this.TxtPrecioCubierto.BorderThickness = 1;
            this.TxtPrecioCubierto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPrecioCubierto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecioCubierto.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtPrecioCubierto.DefaultText = "";
            this.TxtPrecioCubierto.FillColor = System.Drawing.Color.White;
            this.TxtPrecioCubierto.HideSelection = true;
            this.TxtPrecioCubierto.IconLeft = null;
            this.TxtPrecioCubierto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecioCubierto.IconPadding = 10;
            this.TxtPrecioCubierto.IconRight = null;
            this.TxtPrecioCubierto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecioCubierto.Lines = new string[0];
            this.TxtPrecioCubierto.Location = new System.Drawing.Point(422, 133);
            this.TxtPrecioCubierto.MaxLength = 32767;
            this.TxtPrecioCubierto.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPrecioCubierto.Modified = false;
            this.TxtPrecioCubierto.Multiline = false;
            this.TxtPrecioCubierto.Name = "TxtPrecioCubierto";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecioCubierto.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPrecioCubierto.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecioCubierto.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecioCubierto.OnIdleState = stateProperties4;
            this.TxtPrecioCubierto.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPrecioCubierto.PasswordChar = '\0';
            this.TxtPrecioCubierto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrecioCubierto.PlaceholderText = "Enter text";
            this.TxtPrecioCubierto.ReadOnly = false;
            this.TxtPrecioCubierto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPrecioCubierto.SelectedText = "";
            this.TxtPrecioCubierto.SelectionLength = 0;
            this.TxtPrecioCubierto.SelectionStart = 0;
            this.TxtPrecioCubierto.ShortcutsEnabled = true;
            this.TxtPrecioCubierto.Size = new System.Drawing.Size(294, 37);
            this.TxtPrecioCubierto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtPrecioCubierto.TabIndex = 31;
            this.TxtPrecioCubierto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPrecioCubierto.TextMarginBottom = 0;
            this.TxtPrecioCubierto.TextMarginLeft = 3;
            this.TxtPrecioCubierto.TextMarginTop = 0;
            this.TxtPrecioCubierto.TextPlaceholder = "Enter text";
            this.TxtPrecioCubierto.UseSystemPasswordChar = false;
            this.TxtPrecioCubierto.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel8.Location = new System.Drawing.Point(423, 109);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(135, 21);
            this.bunifuLabel8.TabIndex = 30;
            this.bunifuLabel8.Text = "Precio por cubierto:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblErrorPrecio
            // 
            this.LblErrorPrecio.AllowParentOverrides = false;
            this.LblErrorPrecio.AutoEllipsis = false;
            this.LblErrorPrecio.CursorType = null;
            this.LblErrorPrecio.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorPrecio.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorPrecio.Location = new System.Drawing.Point(422, 81);
            this.LblErrorPrecio.Name = "LblErrorPrecio";
            this.LblErrorPrecio.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorPrecio.Size = new System.Drawing.Size(108, 15);
            this.LblErrorPrecio.TabIndex = 29;
            this.LblErrorPrecio.Text = "Debe ingresar precio";
            this.LblErrorPrecio.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorPrecio.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorPrecio.Visible = false;
            // 
            // TxtPrecio
            // 
            this.TxtPrecio.AcceptsReturn = false;
            this.TxtPrecio.AcceptsTab = false;
            this.TxtPrecio.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.TxtPrecio.AnimationSpeed = 200;
            this.TxtPrecio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPrecio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPrecio.AutoSize = true;
            this.TxtPrecio.BackColor = System.Drawing.Color.Transparent;
            this.TxtPrecio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPrecio.BackgroundImage")));
            this.TxtPrecio.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtPrecio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPrecio.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtPrecio.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPrecio.BorderRadius = 1;
            this.TxtPrecio.BorderThickness = 1;
            this.TxtPrecio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPrecio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecio.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtPrecio.DefaultText = "";
            this.TxtPrecio.FillColor = System.Drawing.Color.White;
            this.TxtPrecio.HideSelection = true;
            this.TxtPrecio.IconLeft = null;
            this.TxtPrecio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecio.IconPadding = 10;
            this.TxtPrecio.IconRight = null;
            this.TxtPrecio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrecio.Lines = new string[0];
            this.TxtPrecio.Location = new System.Drawing.Point(422, 42);
            this.TxtPrecio.MaxLength = 32767;
            this.TxtPrecio.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPrecio.Modified = false;
            this.TxtPrecio.Multiline = false;
            this.TxtPrecio.Name = "TxtPrecio";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecio.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPrecio.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecio.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtPrecio.OnIdleState = stateProperties8;
            this.TxtPrecio.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPrecio.PasswordChar = '\0';
            this.TxtPrecio.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrecio.PlaceholderText = "Enter text";
            this.TxtPrecio.ReadOnly = false;
            this.TxtPrecio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPrecio.SelectedText = "";
            this.TxtPrecio.SelectionLength = 0;
            this.TxtPrecio.SelectionStart = 0;
            this.TxtPrecio.ShortcutsEnabled = true;
            this.TxtPrecio.Size = new System.Drawing.Size(294, 37);
            this.TxtPrecio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtPrecio.TabIndex = 28;
            this.TxtPrecio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPrecio.TextMarginBottom = 0;
            this.TxtPrecio.TextMarginLeft = 3;
            this.TxtPrecio.TextMarginTop = 0;
            this.TxtPrecio.TextPlaceholder = "Enter text";
            this.TxtPrecio.UseSystemPasswordChar = false;
            this.TxtPrecio.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel6.Location = new System.Drawing.Point(422, 18);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(46, 21);
            this.bunifuLabel6.TabIndex = 27;
            this.bunifuLabel6.Text = "Precio:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblErrorCapacidad
            // 
            this.LblErrorCapacidad.AllowParentOverrides = false;
            this.LblErrorCapacidad.AutoEllipsis = false;
            this.LblErrorCapacidad.CursorType = null;
            this.LblErrorCapacidad.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorCapacidad.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorCapacidad.Location = new System.Drawing.Point(10, 246);
            this.LblErrorCapacidad.Name = "LblErrorCapacidad";
            this.LblErrorCapacidad.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorCapacidad.Size = new System.Drawing.Size(129, 15);
            this.LblErrorCapacidad.TabIndex = 26;
            this.LblErrorCapacidad.Text = "Debe ingresar capacidad";
            this.LblErrorCapacidad.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorCapacidad.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorCapacidad.Visible = false;
            // 
            // LblErrorUbicacion
            // 
            this.LblErrorUbicacion.AllowParentOverrides = false;
            this.LblErrorUbicacion.AutoEllipsis = false;
            this.LblErrorUbicacion.CursorType = null;
            this.LblErrorUbicacion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorUbicacion.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorUbicacion.Location = new System.Drawing.Point(10, 172);
            this.LblErrorUbicacion.Name = "LblErrorUbicacion";
            this.LblErrorUbicacion.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorUbicacion.Size = new System.Drawing.Size(127, 15);
            this.LblErrorUbicacion.TabIndex = 25;
            this.LblErrorUbicacion.Text = "Debe ingresar ubicación";
            this.LblErrorUbicacion.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorUbicacion.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorUbicacion.Visible = false;
            // 
            // LblErrorPrecioCubierto
            // 
            this.LblErrorPrecioCubierto.AllowParentOverrides = false;
            this.LblErrorPrecioCubierto.AutoEllipsis = false;
            this.LblErrorPrecioCubierto.CursorType = null;
            this.LblErrorPrecioCubierto.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorPrecioCubierto.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorPrecioCubierto.Location = new System.Drawing.Point(423, 172);
            this.LblErrorPrecioCubierto.Name = "LblErrorPrecioCubierto";
            this.LblErrorPrecioCubierto.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorPrecioCubierto.Size = new System.Drawing.Size(92, 15);
            this.LblErrorPrecioCubierto.TabIndex = 24;
            this.LblErrorPrecioCubierto.Text = "Debe ingresar dni";
            this.LblErrorPrecioCubierto.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorPrecioCubierto.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorPrecioCubierto.Visible = false;
            // 
            // LblErrorNombre
            // 
            this.LblErrorNombre.AllowParentOverrides = false;
            this.LblErrorNombre.AutoEllipsis = false;
            this.LblErrorNombre.CursorType = null;
            this.LblErrorNombre.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorNombre.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorNombre.Location = new System.Drawing.Point(10, 81);
            this.LblErrorNombre.Name = "LblErrorNombre";
            this.LblErrorNombre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorNombre.Size = new System.Drawing.Size(129, 15);
            this.LblErrorNombre.TabIndex = 23;
            this.LblErrorNombre.Text = "Debe Ingresar el nombre";
            this.LblErrorNombre.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorNombre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorNombre.Visible = false;
            // 
            // BtnCancelar
            // 
            this.BtnCancelar.AllowAnimations = true;
            this.BtnCancelar.AllowMouseEffects = true;
            this.BtnCancelar.AllowToggling = false;
            this.BtnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCancelar.AnimationSpeed = 200;
            this.BtnCancelar.AutoGenerateColors = false;
            this.BtnCancelar.AutoRoundBorders = false;
            this.BtnCancelar.AutoSizeLeftIcon = true;
            this.BtnCancelar.AutoSizeRightIcon = true;
            this.BtnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancelar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancelar.BackgroundImage")));
            this.BtnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.ButtonText = "Cancelar";
            this.BtnCancelar.ButtonTextMarginLeft = 0;
            this.BtnCancelar.ColorContrastOnClick = 45;
            this.BtnCancelar.ColorContrastOnHover = 45;
            this.BtnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnCancelar.CustomizableEdges = borderEdges1;
            this.BtnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancelar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancelar.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancelar.IconMarginLeft = 11;
            this.BtnCancelar.IconPadding = 10;
            this.BtnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancelar.IconSize = 25;
            this.BtnCancelar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleBorderRadius = 1;
            this.BtnCancelar.IdleBorderThickness = 1;
            this.BtnCancelar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleIconLeftImage = null;
            this.BtnCancelar.IdleIconRightImage = null;
            this.BtnCancelar.IndicateFocus = false;
            this.BtnCancelar.Location = new System.Drawing.Point(736, 172);
            this.BtnCancelar.Name = "BtnCancelar";
            this.BtnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.OnDisabledState.BorderRadius = 1;
            this.BtnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnDisabledState.BorderThickness = 1;
            this.BtnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.OnDisabledState.IconLeftImage = null;
            this.BtnCancelar.OnDisabledState.IconRightImage = null;
            this.BtnCancelar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.BorderRadius = 1;
            this.BtnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.onHoverState.BorderThickness = 1;
            this.BtnCancelar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.onHoverState.IconLeftImage = null;
            this.BtnCancelar.onHoverState.IconRightImage = null;
            this.BtnCancelar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.BorderRadius = 1;
            this.BtnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnIdleState.BorderThickness = 1;
            this.BtnCancelar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.IconLeftImage = null;
            this.BtnCancelar.OnIdleState.IconRightImage = null;
            this.BtnCancelar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCancelar.OnPressedState.BorderRadius = 1;
            this.BtnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnPressedState.BorderThickness = 1;
            this.BtnCancelar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.IconLeftImage = null;
            this.BtnCancelar.OnPressedState.IconRightImage = null;
            this.BtnCancelar.Size = new System.Drawing.Size(150, 39);
            this.BtnCancelar.TabIndex = 22;
            this.BtnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancelar.TextMarginLeft = 0;
            this.BtnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancelar.UseDefaultRadiusAndThickness = true;
            this.BtnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // BtnGuardar
            // 
            this.BtnGuardar.AllowAnimations = true;
            this.BtnGuardar.AllowMouseEffects = true;
            this.BtnGuardar.AllowToggling = false;
            this.BtnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnGuardar.AnimationSpeed = 200;
            this.BtnGuardar.AutoGenerateColors = false;
            this.BtnGuardar.AutoRoundBorders = false;
            this.BtnGuardar.AutoSizeLeftIcon = true;
            this.BtnGuardar.AutoSizeRightIcon = true;
            this.BtnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.BtnGuardar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGuardar.BackgroundImage")));
            this.BtnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.ButtonText = "Guardar";
            this.BtnGuardar.ButtonTextMarginLeft = 0;
            this.BtnGuardar.ColorContrastOnClick = 45;
            this.BtnGuardar.ColorContrastOnHover = 45;
            this.BtnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnGuardar.CustomizableEdges = borderEdges2;
            this.BtnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGuardar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnGuardar.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGuardar.IconMarginLeft = 11;
            this.BtnGuardar.IconPadding = 10;
            this.BtnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGuardar.IconSize = 25;
            this.BtnGuardar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleBorderRadius = 1;
            this.BtnGuardar.IdleBorderThickness = 1;
            this.BtnGuardar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleIconLeftImage = null;
            this.BtnGuardar.IdleIconRightImage = null;
            this.BtnGuardar.IndicateFocus = false;
            this.BtnGuardar.Location = new System.Drawing.Point(736, 81);
            this.BtnGuardar.Name = "BtnGuardar";
            this.BtnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.OnDisabledState.BorderRadius = 1;
            this.BtnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnDisabledState.BorderThickness = 1;
            this.BtnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.OnDisabledState.IconLeftImage = null;
            this.BtnGuardar.OnDisabledState.IconRightImage = null;
            this.BtnGuardar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.BorderRadius = 1;
            this.BtnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.onHoverState.BorderThickness = 1;
            this.BtnGuardar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.onHoverState.IconLeftImage = null;
            this.BtnGuardar.onHoverState.IconRightImage = null;
            this.BtnGuardar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.BorderRadius = 1;
            this.BtnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnIdleState.BorderThickness = 1;
            this.BtnGuardar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnIdleState.IconLeftImage = null;
            this.BtnGuardar.OnIdleState.IconRightImage = null;
            this.BtnGuardar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGuardar.OnPressedState.BorderRadius = 1;
            this.BtnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnPressedState.BorderThickness = 1;
            this.BtnGuardar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnPressedState.IconLeftImage = null;
            this.BtnGuardar.OnPressedState.IconRightImage = null;
            this.BtnGuardar.Size = new System.Drawing.Size(150, 39);
            this.BtnGuardar.TabIndex = 21;
            this.BtnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGuardar.TextMarginLeft = 0;
            this.BtnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGuardar.UseDefaultRadiusAndThickness = true;
            this.BtnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel2.Location = new System.Drawing.Point(10, 18);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(61, 21);
            this.bunifuLabel2.TabIndex = 15;
            this.bunifuLabel2.Text = "Nombre:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtNombre
            // 
            this.TxtNombre.AcceptsReturn = false;
            this.TxtNombre.AcceptsTab = false;
            this.TxtNombre.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.TxtNombre.AnimationSpeed = 200;
            this.TxtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombre.AutoSize = true;
            this.TxtNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombre.BackgroundImage")));
            this.TxtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombre.BorderRadius = 1;
            this.TxtNombre.BorderThickness = 1;
            this.TxtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombre.DefaultText = "";
            this.TxtNombre.FillColor = System.Drawing.Color.White;
            this.TxtNombre.HideSelection = true;
            this.TxtNombre.IconLeft = null;
            this.TxtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.IconPadding = 10;
            this.TxtNombre.IconRight = null;
            this.TxtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.Lines = new string[0];
            this.TxtNombre.Location = new System.Drawing.Point(9, 42);
            this.TxtNombre.MaxLength = 32767;
            this.TxtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombre.Modified = false;
            this.TxtNombre.Multiline = false;
            this.TxtNombre.Name = "TxtNombre";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombre.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnIdleState = stateProperties12;
            this.TxtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNombre.PasswordChar = '\0';
            this.TxtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombre.PlaceholderText = "Enter text";
            this.TxtNombre.ReadOnly = false;
            this.TxtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombre.SelectedText = "";
            this.TxtNombre.SelectionLength = 0;
            this.TxtNombre.SelectionStart = 0;
            this.TxtNombre.ShortcutsEnabled = true;
            this.TxtNombre.Size = new System.Drawing.Size(294, 37);
            this.TxtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombre.TabIndex = 11;
            this.TxtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombre.TextMarginBottom = 0;
            this.TxtNombre.TextMarginLeft = 3;
            this.TxtNombre.TextMarginTop = 0;
            this.TxtNombre.TextPlaceholder = "Enter text";
            this.TxtNombre.UseSystemPasswordChar = false;
            this.TxtNombre.WordWrap = true;
            // 
            // TxtUbicacion
            // 
            this.TxtUbicacion.AcceptsReturn = false;
            this.TxtUbicacion.AcceptsTab = false;
            this.TxtUbicacion.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.TxtUbicacion.AnimationSpeed = 200;
            this.TxtUbicacion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtUbicacion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtUbicacion.AutoSize = true;
            this.TxtUbicacion.BackColor = System.Drawing.Color.Transparent;
            this.TxtUbicacion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtUbicacion.BackgroundImage")));
            this.TxtUbicacion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtUbicacion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtUbicacion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtUbicacion.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtUbicacion.BorderRadius = 1;
            this.TxtUbicacion.BorderThickness = 1;
            this.TxtUbicacion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtUbicacion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUbicacion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtUbicacion.DefaultText = "";
            this.TxtUbicacion.FillColor = System.Drawing.Color.White;
            this.TxtUbicacion.HideSelection = true;
            this.TxtUbicacion.IconLeft = null;
            this.TxtUbicacion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUbicacion.IconPadding = 10;
            this.TxtUbicacion.IconRight = null;
            this.TxtUbicacion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtUbicacion.Lines = new string[0];
            this.TxtUbicacion.Location = new System.Drawing.Point(9, 133);
            this.TxtUbicacion.MaxLength = 32767;
            this.TxtUbicacion.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtUbicacion.Modified = false;
            this.TxtUbicacion.Multiline = false;
            this.TxtUbicacion.Name = "TxtUbicacion";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUbicacion.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtUbicacion.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUbicacion.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtUbicacion.OnIdleState = stateProperties16;
            this.TxtUbicacion.Padding = new System.Windows.Forms.Padding(3);
            this.TxtUbicacion.PasswordChar = '\0';
            this.TxtUbicacion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtUbicacion.PlaceholderText = "Enter text";
            this.TxtUbicacion.ReadOnly = false;
            this.TxtUbicacion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtUbicacion.SelectedText = "";
            this.TxtUbicacion.SelectionLength = 0;
            this.TxtUbicacion.SelectionStart = 0;
            this.TxtUbicacion.ShortcutsEnabled = true;
            this.TxtUbicacion.Size = new System.Drawing.Size(294, 37);
            this.TxtUbicacion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtUbicacion.TabIndex = 12;
            this.TxtUbicacion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtUbicacion.TextMarginBottom = 0;
            this.TxtUbicacion.TextMarginLeft = 3;
            this.TxtUbicacion.TextMarginTop = 0;
            this.TxtUbicacion.TextPlaceholder = "Enter text";
            this.TxtUbicacion.UseSystemPasswordChar = false;
            this.TxtUbicacion.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel5.Location = new System.Drawing.Point(422, 193);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(189, 21);
            this.bunifuLabel5.TabIndex = 18;
            this.bunifuLabel5.Text = "Cantidad minima invitados:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel4.Location = new System.Drawing.Point(10, 193);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(75, 21);
            this.bunifuLabel4.TabIndex = 17;
            this.bunifuLabel4.Text = "Capacidad:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel3.Location = new System.Drawing.Point(10, 109);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(71, 21);
            this.bunifuLabel3.TabIndex = 16;
            this.bunifuLabel3.Text = "Ubicación:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnEliminar
            // 
            this.BtnEliminar.AllowAnimations = true;
            this.BtnEliminar.AllowMouseEffects = true;
            this.BtnEliminar.AllowToggling = false;
            this.BtnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnEliminar.AnimationSpeed = 200;
            this.BtnEliminar.AutoGenerateColors = false;
            this.BtnEliminar.AutoRoundBorders = false;
            this.BtnEliminar.AutoSizeLeftIcon = true;
            this.BtnEliminar.AutoSizeRightIcon = true;
            this.BtnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.BtnEliminar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEliminar.BackgroundImage")));
            this.BtnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.ButtonText = "Eliminar";
            this.BtnEliminar.ButtonTextMarginLeft = 0;
            this.BtnEliminar.ColorContrastOnClick = 45;
            this.BtnEliminar.ColorContrastOnHover = 45;
            this.BtnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnEliminar.CustomizableEdges = borderEdges3;
            this.BtnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnEliminar.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEliminar.IconMarginLeft = 11;
            this.BtnEliminar.IconPadding = 10;
            this.BtnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEliminar.IconSize = 25;
            this.BtnEliminar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleBorderRadius = 1;
            this.BtnEliminar.IdleBorderThickness = 1;
            this.BtnEliminar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleIconLeftImage = null;
            this.BtnEliminar.IdleIconRightImage = null;
            this.BtnEliminar.IndicateFocus = false;
            this.BtnEliminar.Location = new System.Drawing.Point(739, 232);
            this.BtnEliminar.Name = "BtnEliminar";
            this.BtnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.OnDisabledState.BorderRadius = 1;
            this.BtnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnDisabledState.BorderThickness = 1;
            this.BtnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.OnDisabledState.IconLeftImage = null;
            this.BtnEliminar.OnDisabledState.IconRightImage = null;
            this.BtnEliminar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.BorderRadius = 1;
            this.BtnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.onHoverState.BorderThickness = 1;
            this.BtnEliminar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.onHoverState.IconLeftImage = null;
            this.BtnEliminar.onHoverState.IconRightImage = null;
            this.BtnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.BorderRadius = 1;
            this.BtnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnIdleState.BorderThickness = 1;
            this.BtnEliminar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnIdleState.IconLeftImage = null;
            this.BtnEliminar.OnIdleState.IconRightImage = null;
            this.BtnEliminar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnEliminar.OnPressedState.BorderRadius = 1;
            this.BtnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnPressedState.BorderThickness = 1;
            this.BtnEliminar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnPressedState.IconLeftImage = null;
            this.BtnEliminar.OnPressedState.IconRightImage = null;
            this.BtnEliminar.Size = new System.Drawing.Size(150, 39);
            this.BtnEliminar.TabIndex = 29;
            this.BtnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEliminar.TextMarginLeft = 0;
            this.BtnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEliminar.UseDefaultRadiusAndThickness = true;
            this.BtnEliminar.Click += new System.EventHandler(this.BtnEliminar_Click);
            // 
            // BtnModificar
            // 
            this.BtnModificar.AllowAnimations = true;
            this.BtnModificar.AllowMouseEffects = true;
            this.BtnModificar.AllowToggling = false;
            this.BtnModificar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnModificar.AnimationSpeed = 200;
            this.BtnModificar.AutoGenerateColors = false;
            this.BtnModificar.AutoRoundBorders = false;
            this.BtnModificar.AutoSizeLeftIcon = true;
            this.BtnModificar.AutoSizeRightIcon = true;
            this.BtnModificar.BackColor = System.Drawing.Color.Transparent;
            this.BtnModificar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnModificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnModificar.BackgroundImage")));
            this.BtnModificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.ButtonText = "Modificar";
            this.BtnModificar.ButtonTextMarginLeft = 0;
            this.BtnModificar.ColorContrastOnClick = 45;
            this.BtnModificar.ColorContrastOnHover = 45;
            this.BtnModificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnModificar.CustomizableEdges = borderEdges4;
            this.BtnModificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnModificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnModificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnModificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnModificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnModificar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnModificar.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnModificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnModificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnModificar.IconMarginLeft = 11;
            this.BtnModificar.IconPadding = 10;
            this.BtnModificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnModificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnModificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnModificar.IconSize = 25;
            this.BtnModificar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnModificar.IdleBorderRadius = 1;
            this.BtnModificar.IdleBorderThickness = 1;
            this.BtnModificar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.IdleIconLeftImage = null;
            this.BtnModificar.IdleIconRightImage = null;
            this.BtnModificar.IndicateFocus = false;
            this.BtnModificar.Location = new System.Drawing.Point(739, 157);
            this.BtnModificar.Name = "BtnModificar";
            this.BtnModificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnModificar.OnDisabledState.BorderRadius = 1;
            this.BtnModificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnDisabledState.BorderThickness = 1;
            this.BtnModificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnModificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnModificar.OnDisabledState.IconLeftImage = null;
            this.BtnModificar.OnDisabledState.IconRightImage = null;
            this.BtnModificar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnModificar.onHoverState.BorderRadius = 1;
            this.BtnModificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.onHoverState.BorderThickness = 1;
            this.BtnModificar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnModificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.onHoverState.IconLeftImage = null;
            this.BtnModificar.onHoverState.IconRightImage = null;
            this.BtnModificar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnIdleState.BorderRadius = 1;
            this.BtnModificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnIdleState.BorderThickness = 1;
            this.BtnModificar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.OnIdleState.IconLeftImage = null;
            this.BtnModificar.OnIdleState.IconRightImage = null;
            this.BtnModificar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnModificar.OnPressedState.BorderRadius = 1;
            this.BtnModificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnPressedState.BorderThickness = 1;
            this.BtnModificar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.OnPressedState.IconLeftImage = null;
            this.BtnModificar.OnPressedState.IconRightImage = null;
            this.BtnModificar.Size = new System.Drawing.Size(150, 39);
            this.BtnModificar.TabIndex = 27;
            this.BtnModificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnModificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnModificar.TextMarginLeft = 0;
            this.BtnModificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnModificar.UseDefaultRadiusAndThickness = true;
            this.BtnModificar.Click += new System.EventHandler(this.BtnModificar_Click);
            // 
            // BtnCrear
            // 
            this.BtnCrear.AllowAnimations = true;
            this.BtnCrear.AllowMouseEffects = true;
            this.BtnCrear.AllowToggling = false;
            this.BtnCrear.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCrear.AnimationSpeed = 200;
            this.BtnCrear.AutoGenerateColors = false;
            this.BtnCrear.AutoRoundBorders = false;
            this.BtnCrear.AutoSizeLeftIcon = true;
            this.BtnCrear.AutoSizeRightIcon = true;
            this.BtnCrear.BackColor = System.Drawing.Color.Transparent;
            this.BtnCrear.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCrear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCrear.BackgroundImage")));
            this.BtnCrear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.ButtonText = "Crear";
            this.BtnCrear.ButtonTextMarginLeft = 0;
            this.BtnCrear.ColorContrastOnClick = 45;
            this.BtnCrear.ColorContrastOnHover = 45;
            this.BtnCrear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnCrear.CustomizableEdges = borderEdges5;
            this.BtnCrear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCrear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCrear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCrear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCrear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCrear.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCrear.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCrear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCrear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCrear.IconMarginLeft = 11;
            this.BtnCrear.IconPadding = 10;
            this.BtnCrear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCrear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCrear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCrear.IconSize = 25;
            this.BtnCrear.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCrear.IdleBorderRadius = 1;
            this.BtnCrear.IdleBorderThickness = 1;
            this.BtnCrear.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.IdleIconLeftImage = null;
            this.BtnCrear.IdleIconRightImage = null;
            this.BtnCrear.IndicateFocus = false;
            this.BtnCrear.Location = new System.Drawing.Point(739, 87);
            this.BtnCrear.Name = "BtnCrear";
            this.BtnCrear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCrear.OnDisabledState.BorderRadius = 1;
            this.BtnCrear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnDisabledState.BorderThickness = 1;
            this.BtnCrear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCrear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCrear.OnDisabledState.IconLeftImage = null;
            this.BtnCrear.OnDisabledState.IconRightImage = null;
            this.BtnCrear.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCrear.onHoverState.BorderRadius = 1;
            this.BtnCrear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.onHoverState.BorderThickness = 1;
            this.BtnCrear.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCrear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.onHoverState.IconLeftImage = null;
            this.BtnCrear.onHoverState.IconRightImage = null;
            this.BtnCrear.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnIdleState.BorderRadius = 1;
            this.BtnCrear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnIdleState.BorderThickness = 1;
            this.BtnCrear.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.OnIdleState.IconLeftImage = null;
            this.BtnCrear.OnIdleState.IconRightImage = null;
            this.BtnCrear.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCrear.OnPressedState.BorderRadius = 1;
            this.BtnCrear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnPressedState.BorderThickness = 1;
            this.BtnCrear.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.OnPressedState.IconLeftImage = null;
            this.BtnCrear.OnPressedState.IconRightImage = null;
            this.BtnCrear.Size = new System.Drawing.Size(150, 39);
            this.BtnCrear.TabIndex = 26;
            this.BtnCrear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCrear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCrear.TextMarginLeft = 0;
            this.BtnCrear.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCrear.UseDefaultRadiusAndThickness = true;
            this.BtnCrear.Click += new System.EventHandler(this.BtnCrear_Click);
            // 
            // DataGridViewSalones
            // 
            this.DataGridViewSalones.AllowCustomTheming = false;
            this.DataGridViewSalones.AllowUserToAddRows = false;
            this.DataGridViewSalones.AllowUserToDeleteRows = false;
            this.DataGridViewSalones.AllowUserToResizeColumns = false;
            this.DataGridViewSalones.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewSalones.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DataGridViewSalones.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.DataGridViewSalones.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DataGridViewSalones.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DataGridViewSalones.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DataGridViewSalones.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DataGridViewSalones.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.DataGridViewSalones.ColumnHeadersHeight = 40;
            this.DataGridViewSalones.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.DataGridViewSalones.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewSalones.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewSalones.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DataGridViewSalones.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DataGridViewSalones.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.DataGridViewSalones.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DataGridViewSalones.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.DataGridViewSalones.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewSalones.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DataGridViewSalones.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.DataGridViewSalones.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DataGridViewSalones.CurrentTheme.Name = null;
            this.DataGridViewSalones.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.DataGridViewSalones.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewSalones.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewSalones.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DataGridViewSalones.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DataGridViewSalones.DefaultCellStyle = dataGridViewCellStyle3;
            this.DataGridViewSalones.EnableHeadersVisualStyles = false;
            this.DataGridViewSalones.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DataGridViewSalones.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.DataGridViewSalones.HeaderBgColor = System.Drawing.Color.Empty;
            this.DataGridViewSalones.HeaderForeColor = System.Drawing.Color.White;
            this.DataGridViewSalones.Location = new System.Drawing.Point(12, 87);
            this.DataGridViewSalones.MultiSelect = false;
            this.DataGridViewSalones.Name = "DataGridViewSalones";
            this.DataGridViewSalones.ReadOnly = true;
            this.DataGridViewSalones.RowHeadersVisible = false;
            this.DataGridViewSalones.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DataGridViewSalones.RowTemplate.Height = 40;
            this.DataGridViewSalones.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DataGridViewSalones.ShowCellErrors = false;
            this.DataGridViewSalones.ShowCellToolTips = false;
            this.DataGridViewSalones.ShowEditingIcon = false;
            this.DataGridViewSalones.ShowRowErrors = false;
            this.DataGridViewSalones.Size = new System.Drawing.Size(708, 184);
            this.DataGridViewSalones.TabIndex = 25;
            this.DataGridViewSalones.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.DataGridViewSalones.DataBindingComplete += new System.Windows.Forms.DataGridViewBindingCompleteEventHandler(this.DataGridViewSalones_DataBindingComplete);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 20.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 21);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(242, 45);
            this.bunifuLabel1.TabIndex = 24;
            this.bunifuLabel1.Text = "Gestión de salón";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // FormGestionSalon
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(901, 611);
            this.Controls.Add(this.PanelData);
            this.Controls.Add(this.BtnEliminar);
            this.Controls.Add(this.BtnModificar);
            this.Controls.Add(this.BtnCrear);
            this.Controls.Add(this.DataGridViewSalones);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormGestionSalon";
            this.Text = "FormGestionSalon";
            this.PanelData.ResumeLayout(false);
            this.PanelData.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.NumCantidadMinimaInvitados)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.NumCapacidad)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewSalones)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Panel PanelData;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorCapacidad;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorUbicacion;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorPrecioCubierto;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorNombre;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancelar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGuardar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombre;
        private Bunifu.UI.WinForms.BunifuTextBox TxtUbicacion;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnModificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCrear;
        private Bunifu.UI.WinForms.BunifuDataGridView DataGridViewSalones;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPrecio;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorPrecio;
        private System.Windows.Forms.NumericUpDown NumCantidadMinimaInvitados;
        private System.Windows.Forms.NumericUpDown NumCapacidad;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPrecioCubierto;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorCantidadMinimaInvitados;
    }
}