namespace UI
{
    partial class FormMenuPrincipal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMenuPrincipal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.PanelSideMenu = new System.Windows.Forms.Panel();
            this.BtnCambiarPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel5 = new Bunifu.UI.WinForms.BunifuPanel();
            this.BtnAyuda = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.BtnGestionUsuarios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.BtnCobranza = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.BtnRealizarReserva = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.BtnInicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCerrarSesion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.PanelContenedor = new System.Windows.Forms.Panel();
            this.PanelSideMenu.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // PanelSideMenu
            // 
            this.PanelSideMenu.BackColor = System.Drawing.Color.LightSlateGray;
            this.PanelSideMenu.Controls.Add(this.BtnCambiarPassword);
            this.PanelSideMenu.Controls.Add(this.bunifuPanel5);
            this.PanelSideMenu.Controls.Add(this.BtnAyuda);
            this.PanelSideMenu.Controls.Add(this.bunifuPanel2);
            this.PanelSideMenu.Controls.Add(this.BtnGestionUsuarios);
            this.PanelSideMenu.Controls.Add(this.bunifuPanel4);
            this.PanelSideMenu.Controls.Add(this.BtnCobranza);
            this.PanelSideMenu.Controls.Add(this.bunifuPanel1);
            this.PanelSideMenu.Controls.Add(this.BtnRealizarReserva);
            this.PanelSideMenu.Controls.Add(this.bunifuPanel3);
            this.PanelSideMenu.Controls.Add(this.BtnInicio);
            this.PanelSideMenu.Controls.Add(this.BtnCerrarSesion);
            this.PanelSideMenu.Controls.Add(this.panel1);
            this.PanelSideMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.PanelSideMenu.Location = new System.Drawing.Point(0, 0);
            this.PanelSideMenu.Name = "PanelSideMenu";
            this.PanelSideMenu.Size = new System.Drawing.Size(233, 611);
            this.PanelSideMenu.TabIndex = 0;
            // 
            // BtnCambiarPassword
            // 
            this.BtnCambiarPassword.AllowAnimations = true;
            this.BtnCambiarPassword.AllowMouseEffects = true;
            this.BtnCambiarPassword.AllowToggling = false;
            this.BtnCambiarPassword.AnimationSpeed = 200;
            this.BtnCambiarPassword.AutoGenerateColors = false;
            this.BtnCambiarPassword.AutoRoundBorders = false;
            this.BtnCambiarPassword.AutoSizeLeftIcon = true;
            this.BtnCambiarPassword.AutoSizeRightIcon = true;
            this.BtnCambiarPassword.BackColor = System.Drawing.Color.Transparent;
            this.BtnCambiarPassword.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCambiarPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCambiarPassword.BackgroundImage")));
            this.BtnCambiarPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCambiarPassword.ButtonText = "Cambiar Contraseña";
            this.BtnCambiarPassword.ButtonTextMarginLeft = 0;
            this.BtnCambiarPassword.ColorContrastOnClick = 45;
            this.BtnCambiarPassword.ColorContrastOnHover = 45;
            this.BtnCambiarPassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnCambiarPassword.CustomizableEdges = borderEdges1;
            this.BtnCambiarPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCambiarPassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCambiarPassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCambiarPassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCambiarPassword.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.BtnCambiarPassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCambiarPassword.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCambiarPassword.ForeColor = System.Drawing.Color.White;
            this.BtnCambiarPassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCambiarPassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCambiarPassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCambiarPassword.IconMarginLeft = 11;
            this.BtnCambiarPassword.IconPadding = 10;
            this.BtnCambiarPassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCambiarPassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCambiarPassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCambiarPassword.IconSize = 25;
            this.BtnCambiarPassword.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnCambiarPassword.IdleBorderRadius = 1;
            this.BtnCambiarPassword.IdleBorderThickness = 1;
            this.BtnCambiarPassword.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCambiarPassword.IdleIconLeftImage = null;
            this.BtnCambiarPassword.IdleIconRightImage = null;
            this.BtnCambiarPassword.IndicateFocus = false;
            this.BtnCambiarPassword.Location = new System.Drawing.Point(0, 519);
            this.BtnCambiarPassword.Name = "BtnCambiarPassword";
            this.BtnCambiarPassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCambiarPassword.OnDisabledState.BorderRadius = 1;
            this.BtnCambiarPassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCambiarPassword.OnDisabledState.BorderThickness = 1;
            this.BtnCambiarPassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCambiarPassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCambiarPassword.OnDisabledState.IconLeftImage = null;
            this.BtnCambiarPassword.OnDisabledState.IconRightImage = null;
            this.BtnCambiarPassword.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCambiarPassword.onHoverState.BorderRadius = 1;
            this.BtnCambiarPassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCambiarPassword.onHoverState.BorderThickness = 1;
            this.BtnCambiarPassword.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCambiarPassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCambiarPassword.onHoverState.IconLeftImage = null;
            this.BtnCambiarPassword.onHoverState.IconRightImage = null;
            this.BtnCambiarPassword.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCambiarPassword.OnIdleState.BorderRadius = 1;
            this.BtnCambiarPassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCambiarPassword.OnIdleState.BorderThickness = 1;
            this.BtnCambiarPassword.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCambiarPassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCambiarPassword.OnIdleState.IconLeftImage = null;
            this.BtnCambiarPassword.OnIdleState.IconRightImage = null;
            this.BtnCambiarPassword.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCambiarPassword.OnPressedState.BorderRadius = 1;
            this.BtnCambiarPassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCambiarPassword.OnPressedState.BorderThickness = 1;
            this.BtnCambiarPassword.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCambiarPassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCambiarPassword.OnPressedState.IconLeftImage = null;
            this.BtnCambiarPassword.OnPressedState.IconRightImage = null;
            this.BtnCambiarPassword.Size = new System.Drawing.Size(233, 39);
            this.BtnCambiarPassword.TabIndex = 22;
            this.BtnCambiarPassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCambiarPassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCambiarPassword.TextMarginLeft = 0;
            this.BtnCambiarPassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCambiarPassword.UseDefaultRadiusAndThickness = true;
            this.BtnCambiarPassword.Click += new System.EventHandler(this.BtnCambiarPassword_Click);
            // 
            // bunifuPanel5
            // 
            this.bunifuPanel5.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel5.BackgroundImage")));
            this.bunifuPanel5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel5.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel5.BorderRadius = 3;
            this.bunifuPanel5.BorderThickness = 1;
            this.bunifuPanel5.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuPanel5.Location = new System.Drawing.Point(0, 558);
            this.bunifuPanel5.Name = "bunifuPanel5";
            this.bunifuPanel5.ShowBorders = true;
            this.bunifuPanel5.Size = new System.Drawing.Size(233, 14);
            this.bunifuPanel5.TabIndex = 21;
            // 
            // BtnAyuda
            // 
            this.BtnAyuda.AllowAnimations = true;
            this.BtnAyuda.AllowMouseEffects = true;
            this.BtnAyuda.AllowToggling = false;
            this.BtnAyuda.AnimationSpeed = 200;
            this.BtnAyuda.AutoGenerateColors = false;
            this.BtnAyuda.AutoRoundBorders = false;
            this.BtnAyuda.AutoSizeLeftIcon = true;
            this.BtnAyuda.AutoSizeRightIcon = true;
            this.BtnAyuda.BackColor = System.Drawing.Color.Transparent;
            this.BtnAyuda.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnAyuda.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAyuda.BackgroundImage")));
            this.BtnAyuda.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAyuda.ButtonText = "Ayuda";
            this.BtnAyuda.ButtonTextMarginLeft = 0;
            this.BtnAyuda.ColorContrastOnClick = 45;
            this.BtnAyuda.ColorContrastOnHover = 45;
            this.BtnAyuda.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnAyuda.CustomizableEdges = borderEdges2;
            this.BtnAyuda.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAyuda.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAyuda.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAyuda.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAyuda.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnAyuda.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnAyuda.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnAyuda.ForeColor = System.Drawing.Color.White;
            this.BtnAyuda.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAyuda.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAyuda.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAyuda.IconMarginLeft = 11;
            this.BtnAyuda.IconPadding = 10;
            this.BtnAyuda.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAyuda.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAyuda.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAyuda.IconSize = 25;
            this.BtnAyuda.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnAyuda.IdleBorderRadius = 1;
            this.BtnAyuda.IdleBorderThickness = 1;
            this.BtnAyuda.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnAyuda.IdleIconLeftImage = null;
            this.BtnAyuda.IdleIconRightImage = null;
            this.BtnAyuda.IndicateFocus = false;
            this.BtnAyuda.Location = new System.Drawing.Point(0, 356);
            this.BtnAyuda.Name = "BtnAyuda";
            this.BtnAyuda.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAyuda.OnDisabledState.BorderRadius = 1;
            this.BtnAyuda.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAyuda.OnDisabledState.BorderThickness = 1;
            this.BtnAyuda.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAyuda.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAyuda.OnDisabledState.IconLeftImage = null;
            this.BtnAyuda.OnDisabledState.IconRightImage = null;
            this.BtnAyuda.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnAyuda.onHoverState.BorderRadius = 1;
            this.BtnAyuda.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAyuda.onHoverState.BorderThickness = 1;
            this.BtnAyuda.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnAyuda.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnAyuda.onHoverState.IconLeftImage = null;
            this.BtnAyuda.onHoverState.IconRightImage = null;
            this.BtnAyuda.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnAyuda.OnIdleState.BorderRadius = 1;
            this.BtnAyuda.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAyuda.OnIdleState.BorderThickness = 1;
            this.BtnAyuda.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAyuda.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAyuda.OnIdleState.IconLeftImage = null;
            this.BtnAyuda.OnIdleState.IconRightImage = null;
            this.BtnAyuda.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnAyuda.OnPressedState.BorderRadius = 1;
            this.BtnAyuda.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAyuda.OnPressedState.BorderThickness = 1;
            this.BtnAyuda.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAyuda.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAyuda.OnPressedState.IconLeftImage = null;
            this.BtnAyuda.OnPressedState.IconRightImage = null;
            this.BtnAyuda.Size = new System.Drawing.Size(233, 39);
            this.BtnAyuda.TabIndex = 20;
            this.BtnAyuda.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnAyuda.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAyuda.TextMarginLeft = 0;
            this.BtnAyuda.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnAyuda.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 342);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(233, 14);
            this.bunifuPanel2.TabIndex = 19;
            // 
            // BtnGestionUsuarios
            // 
            this.BtnGestionUsuarios.AllowAnimations = true;
            this.BtnGestionUsuarios.AllowMouseEffects = true;
            this.BtnGestionUsuarios.AllowToggling = false;
            this.BtnGestionUsuarios.AnimationSpeed = 200;
            this.BtnGestionUsuarios.AutoGenerateColors = false;
            this.BtnGestionUsuarios.AutoRoundBorders = false;
            this.BtnGestionUsuarios.AutoSizeLeftIcon = true;
            this.BtnGestionUsuarios.AutoSizeRightIcon = true;
            this.BtnGestionUsuarios.BackColor = System.Drawing.Color.Transparent;
            this.BtnGestionUsuarios.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnGestionUsuarios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGestionUsuarios.BackgroundImage")));
            this.BtnGestionUsuarios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGestionUsuarios.ButtonText = "Gestion Usuarios";
            this.BtnGestionUsuarios.ButtonTextMarginLeft = 0;
            this.BtnGestionUsuarios.ColorContrastOnClick = 45;
            this.BtnGestionUsuarios.ColorContrastOnHover = 45;
            this.BtnGestionUsuarios.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnGestionUsuarios.CustomizableEdges = borderEdges3;
            this.BtnGestionUsuarios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGestionUsuarios.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGestionUsuarios.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGestionUsuarios.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGestionUsuarios.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnGestionUsuarios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGestionUsuarios.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnGestionUsuarios.ForeColor = System.Drawing.Color.White;
            this.BtnGestionUsuarios.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGestionUsuarios.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGestionUsuarios.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGestionUsuarios.IconMarginLeft = 11;
            this.BtnGestionUsuarios.IconPadding = 10;
            this.BtnGestionUsuarios.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGestionUsuarios.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGestionUsuarios.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGestionUsuarios.IconSize = 25;
            this.BtnGestionUsuarios.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnGestionUsuarios.IdleBorderRadius = 1;
            this.BtnGestionUsuarios.IdleBorderThickness = 1;
            this.BtnGestionUsuarios.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnGestionUsuarios.IdleIconLeftImage = null;
            this.BtnGestionUsuarios.IdleIconRightImage = null;
            this.BtnGestionUsuarios.IndicateFocus = false;
            this.BtnGestionUsuarios.Location = new System.Drawing.Point(0, 303);
            this.BtnGestionUsuarios.Name = "BtnGestionUsuarios";
            this.BtnGestionUsuarios.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGestionUsuarios.OnDisabledState.BorderRadius = 1;
            this.BtnGestionUsuarios.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGestionUsuarios.OnDisabledState.BorderThickness = 1;
            this.BtnGestionUsuarios.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGestionUsuarios.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGestionUsuarios.OnDisabledState.IconLeftImage = null;
            this.BtnGestionUsuarios.OnDisabledState.IconRightImage = null;
            this.BtnGestionUsuarios.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnGestionUsuarios.onHoverState.BorderRadius = 1;
            this.BtnGestionUsuarios.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGestionUsuarios.onHoverState.BorderThickness = 1;
            this.BtnGestionUsuarios.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnGestionUsuarios.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGestionUsuarios.onHoverState.IconLeftImage = null;
            this.BtnGestionUsuarios.onHoverState.IconRightImage = null;
            this.BtnGestionUsuarios.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGestionUsuarios.OnIdleState.BorderRadius = 1;
            this.BtnGestionUsuarios.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGestionUsuarios.OnIdleState.BorderThickness = 1;
            this.BtnGestionUsuarios.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGestionUsuarios.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGestionUsuarios.OnIdleState.IconLeftImage = null;
            this.BtnGestionUsuarios.OnIdleState.IconRightImage = null;
            this.BtnGestionUsuarios.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGestionUsuarios.OnPressedState.BorderRadius = 1;
            this.BtnGestionUsuarios.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGestionUsuarios.OnPressedState.BorderThickness = 1;
            this.BtnGestionUsuarios.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGestionUsuarios.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGestionUsuarios.OnPressedState.IconLeftImage = null;
            this.BtnGestionUsuarios.OnPressedState.IconRightImage = null;
            this.BtnGestionUsuarios.Size = new System.Drawing.Size(233, 39);
            this.BtnGestionUsuarios.TabIndex = 18;
            this.BtnGestionUsuarios.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGestionUsuarios.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGestionUsuarios.TextMarginLeft = 0;
            this.BtnGestionUsuarios.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGestionUsuarios.UseDefaultRadiusAndThickness = true;
            this.BtnGestionUsuarios.Click += new System.EventHandler(this.BtnGestionUsuarios_Click);
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BorderRadius = 3;
            this.bunifuPanel4.BorderThickness = 1;
            this.bunifuPanel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel4.Location = new System.Drawing.Point(0, 289);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(233, 14);
            this.bunifuPanel4.TabIndex = 17;
            // 
            // BtnCobranza
            // 
            this.BtnCobranza.AllowAnimations = true;
            this.BtnCobranza.AllowMouseEffects = true;
            this.BtnCobranza.AllowToggling = false;
            this.BtnCobranza.AnimationSpeed = 200;
            this.BtnCobranza.AutoGenerateColors = false;
            this.BtnCobranza.AutoRoundBorders = false;
            this.BtnCobranza.AutoSizeLeftIcon = true;
            this.BtnCobranza.AutoSizeRightIcon = true;
            this.BtnCobranza.BackColor = System.Drawing.Color.Transparent;
            this.BtnCobranza.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCobranza.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCobranza.BackgroundImage")));
            this.BtnCobranza.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCobranza.ButtonText = "Cobranza";
            this.BtnCobranza.ButtonTextMarginLeft = 0;
            this.BtnCobranza.ColorContrastOnClick = 45;
            this.BtnCobranza.ColorContrastOnHover = 45;
            this.BtnCobranza.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCobranza.CustomizableEdges = borderEdges4;
            this.BtnCobranza.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCobranza.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCobranza.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCobranza.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCobranza.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnCobranza.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCobranza.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCobranza.ForeColor = System.Drawing.Color.White;
            this.BtnCobranza.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCobranza.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCobranza.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCobranza.IconMarginLeft = 11;
            this.BtnCobranza.IconPadding = 10;
            this.BtnCobranza.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCobranza.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCobranza.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCobranza.IconSize = 25;
            this.BtnCobranza.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnCobranza.IdleBorderRadius = 1;
            this.BtnCobranza.IdleBorderThickness = 1;
            this.BtnCobranza.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCobranza.IdleIconLeftImage = null;
            this.BtnCobranza.IdleIconRightImage = null;
            this.BtnCobranza.IndicateFocus = false;
            this.BtnCobranza.Location = new System.Drawing.Point(0, 250);
            this.BtnCobranza.Name = "BtnCobranza";
            this.BtnCobranza.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCobranza.OnDisabledState.BorderRadius = 1;
            this.BtnCobranza.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCobranza.OnDisabledState.BorderThickness = 1;
            this.BtnCobranza.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCobranza.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCobranza.OnDisabledState.IconLeftImage = null;
            this.BtnCobranza.OnDisabledState.IconRightImage = null;
            this.BtnCobranza.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCobranza.onHoverState.BorderRadius = 1;
            this.BtnCobranza.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCobranza.onHoverState.BorderThickness = 1;
            this.BtnCobranza.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCobranza.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCobranza.onHoverState.IconLeftImage = null;
            this.BtnCobranza.onHoverState.IconRightImage = null;
            this.BtnCobranza.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCobranza.OnIdleState.BorderRadius = 1;
            this.BtnCobranza.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCobranza.OnIdleState.BorderThickness = 1;
            this.BtnCobranza.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCobranza.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCobranza.OnIdleState.IconLeftImage = null;
            this.BtnCobranza.OnIdleState.IconRightImage = null;
            this.BtnCobranza.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCobranza.OnPressedState.BorderRadius = 1;
            this.BtnCobranza.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCobranza.OnPressedState.BorderThickness = 1;
            this.BtnCobranza.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCobranza.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCobranza.OnPressedState.IconLeftImage = null;
            this.BtnCobranza.OnPressedState.IconRightImage = null;
            this.BtnCobranza.Size = new System.Drawing.Size(233, 39);
            this.BtnCobranza.TabIndex = 16;
            this.BtnCobranza.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCobranza.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCobranza.TextMarginLeft = 0;
            this.BtnCobranza.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCobranza.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 236);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(233, 14);
            this.bunifuPanel1.TabIndex = 15;
            // 
            // BtnRealizarReserva
            // 
            this.BtnRealizarReserva.AllowAnimations = true;
            this.BtnRealizarReserva.AllowMouseEffects = true;
            this.BtnRealizarReserva.AllowToggling = false;
            this.BtnRealizarReserva.AnimationSpeed = 200;
            this.BtnRealizarReserva.AutoGenerateColors = false;
            this.BtnRealizarReserva.AutoRoundBorders = false;
            this.BtnRealizarReserva.AutoSizeLeftIcon = true;
            this.BtnRealizarReserva.AutoSizeRightIcon = true;
            this.BtnRealizarReserva.BackColor = System.Drawing.Color.Transparent;
            this.BtnRealizarReserva.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnRealizarReserva.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnRealizarReserva.BackgroundImage")));
            this.BtnRealizarReserva.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRealizarReserva.ButtonText = "Realizar Reserva";
            this.BtnRealizarReserva.ButtonTextMarginLeft = 0;
            this.BtnRealizarReserva.ColorContrastOnClick = 45;
            this.BtnRealizarReserva.ColorContrastOnHover = 45;
            this.BtnRealizarReserva.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnRealizarReserva.CustomizableEdges = borderEdges5;
            this.BtnRealizarReserva.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnRealizarReserva.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRealizarReserva.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnRealizarReserva.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnRealizarReserva.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnRealizarReserva.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnRealizarReserva.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnRealizarReserva.ForeColor = System.Drawing.Color.White;
            this.BtnRealizarReserva.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRealizarReserva.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRealizarReserva.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnRealizarReserva.IconMarginLeft = 11;
            this.BtnRealizarReserva.IconPadding = 10;
            this.BtnRealizarReserva.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnRealizarReserva.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRealizarReserva.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnRealizarReserva.IconSize = 25;
            this.BtnRealizarReserva.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnRealizarReserva.IdleBorderRadius = 1;
            this.BtnRealizarReserva.IdleBorderThickness = 1;
            this.BtnRealizarReserva.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnRealizarReserva.IdleIconLeftImage = null;
            this.BtnRealizarReserva.IdleIconRightImage = null;
            this.BtnRealizarReserva.IndicateFocus = false;
            this.BtnRealizarReserva.Location = new System.Drawing.Point(0, 197);
            this.BtnRealizarReserva.Name = "BtnRealizarReserva";
            this.BtnRealizarReserva.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRealizarReserva.OnDisabledState.BorderRadius = 1;
            this.BtnRealizarReserva.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRealizarReserva.OnDisabledState.BorderThickness = 1;
            this.BtnRealizarReserva.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnRealizarReserva.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnRealizarReserva.OnDisabledState.IconLeftImage = null;
            this.BtnRealizarReserva.OnDisabledState.IconRightImage = null;
            this.BtnRealizarReserva.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnRealizarReserva.onHoverState.BorderRadius = 1;
            this.BtnRealizarReserva.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRealizarReserva.onHoverState.BorderThickness = 1;
            this.BtnRealizarReserva.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnRealizarReserva.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnRealizarReserva.onHoverState.IconLeftImage = null;
            this.BtnRealizarReserva.onHoverState.IconRightImage = null;
            this.BtnRealizarReserva.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnRealizarReserva.OnIdleState.BorderRadius = 1;
            this.BtnRealizarReserva.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRealizarReserva.OnIdleState.BorderThickness = 1;
            this.BtnRealizarReserva.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnRealizarReserva.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnRealizarReserva.OnIdleState.IconLeftImage = null;
            this.BtnRealizarReserva.OnIdleState.IconRightImage = null;
            this.BtnRealizarReserva.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnRealizarReserva.OnPressedState.BorderRadius = 1;
            this.BtnRealizarReserva.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRealizarReserva.OnPressedState.BorderThickness = 1;
            this.BtnRealizarReserva.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnRealizarReserva.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnRealizarReserva.OnPressedState.IconLeftImage = null;
            this.BtnRealizarReserva.OnPressedState.IconRightImage = null;
            this.BtnRealizarReserva.Size = new System.Drawing.Size(233, 39);
            this.BtnRealizarReserva.TabIndex = 14;
            this.BtnRealizarReserva.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnRealizarReserva.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnRealizarReserva.TextMarginLeft = 0;
            this.BtnRealizarReserva.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnRealizarReserva.UseDefaultRadiusAndThickness = true;
            this.BtnRealizarReserva.Click += new System.EventHandler(this.BtnRealizarReserva_Click);
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 3;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel3.Location = new System.Drawing.Point(0, 183);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(233, 14);
            this.bunifuPanel3.TabIndex = 13;
            // 
            // BtnInicio
            // 
            this.BtnInicio.AllowAnimations = true;
            this.BtnInicio.AllowMouseEffects = true;
            this.BtnInicio.AllowToggling = false;
            this.BtnInicio.AnimationSpeed = 200;
            this.BtnInicio.AutoGenerateColors = false;
            this.BtnInicio.AutoRoundBorders = false;
            this.BtnInicio.AutoSizeLeftIcon = true;
            this.BtnInicio.AutoSizeRightIcon = true;
            this.BtnInicio.BackColor = System.Drawing.Color.Transparent;
            this.BtnInicio.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnInicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnInicio.BackgroundImage")));
            this.BtnInicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnInicio.ButtonText = "Inicio";
            this.BtnInicio.ButtonTextMarginLeft = 0;
            this.BtnInicio.ColorContrastOnClick = 45;
            this.BtnInicio.ColorContrastOnHover = 45;
            this.BtnInicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnInicio.CustomizableEdges = borderEdges6;
            this.BtnInicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnInicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnInicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnInicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnInicio.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnInicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnInicio.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnInicio.ForeColor = System.Drawing.Color.White;
            this.BtnInicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnInicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnInicio.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnInicio.IconMarginLeft = 11;
            this.BtnInicio.IconPadding = 10;
            this.BtnInicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnInicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnInicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnInicio.IconSize = 25;
            this.BtnInicio.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnInicio.IdleBorderRadius = 1;
            this.BtnInicio.IdleBorderThickness = 1;
            this.BtnInicio.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnInicio.IdleIconLeftImage = null;
            this.BtnInicio.IdleIconRightImage = null;
            this.BtnInicio.IndicateFocus = false;
            this.BtnInicio.Location = new System.Drawing.Point(0, 144);
            this.BtnInicio.Name = "BtnInicio";
            this.BtnInicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnInicio.OnDisabledState.BorderRadius = 1;
            this.BtnInicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnInicio.OnDisabledState.BorderThickness = 1;
            this.BtnInicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnInicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnInicio.OnDisabledState.IconLeftImage = null;
            this.BtnInicio.OnDisabledState.IconRightImage = null;
            this.BtnInicio.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnInicio.onHoverState.BorderRadius = 1;
            this.BtnInicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnInicio.onHoverState.BorderThickness = 1;
            this.BtnInicio.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnInicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnInicio.onHoverState.IconLeftImage = null;
            this.BtnInicio.onHoverState.IconRightImage = null;
            this.BtnInicio.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnInicio.OnIdleState.BorderRadius = 1;
            this.BtnInicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnInicio.OnIdleState.BorderThickness = 1;
            this.BtnInicio.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnInicio.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnInicio.OnIdleState.IconLeftImage = null;
            this.BtnInicio.OnIdleState.IconRightImage = null;
            this.BtnInicio.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnInicio.OnPressedState.BorderRadius = 1;
            this.BtnInicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnInicio.OnPressedState.BorderThickness = 1;
            this.BtnInicio.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnInicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnInicio.OnPressedState.IconLeftImage = null;
            this.BtnInicio.OnPressedState.IconRightImage = null;
            this.BtnInicio.Size = new System.Drawing.Size(233, 39);
            this.BtnInicio.TabIndex = 13;
            this.BtnInicio.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnInicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnInicio.TextMarginLeft = 0;
            this.BtnInicio.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnInicio.UseDefaultRadiusAndThickness = true;
            this.BtnInicio.Click += new System.EventHandler(this.BtnInicio_Click);
            // 
            // BtnCerrarSesion
            // 
            this.BtnCerrarSesion.AllowAnimations = true;
            this.BtnCerrarSesion.AllowMouseEffects = true;
            this.BtnCerrarSesion.AllowToggling = false;
            this.BtnCerrarSesion.AnimationSpeed = 200;
            this.BtnCerrarSesion.AutoGenerateColors = false;
            this.BtnCerrarSesion.AutoRoundBorders = false;
            this.BtnCerrarSesion.AutoSizeLeftIcon = true;
            this.BtnCerrarSesion.AutoSizeRightIcon = true;
            this.BtnCerrarSesion.BackColor = System.Drawing.Color.Transparent;
            this.BtnCerrarSesion.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCerrarSesion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCerrarSesion.BackgroundImage")));
            this.BtnCerrarSesion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCerrarSesion.ButtonText = "Cerrar Sesión";
            this.BtnCerrarSesion.ButtonTextMarginLeft = 0;
            this.BtnCerrarSesion.ColorContrastOnClick = 45;
            this.BtnCerrarSesion.ColorContrastOnHover = 45;
            this.BtnCerrarSesion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnCerrarSesion.CustomizableEdges = borderEdges7;
            this.BtnCerrarSesion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCerrarSesion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCerrarSesion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCerrarSesion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCerrarSesion.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.BtnCerrarSesion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCerrarSesion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCerrarSesion.ForeColor = System.Drawing.Color.White;
            this.BtnCerrarSesion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCerrarSesion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCerrarSesion.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCerrarSesion.IconMarginLeft = 11;
            this.BtnCerrarSesion.IconPadding = 10;
            this.BtnCerrarSesion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCerrarSesion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCerrarSesion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCerrarSesion.IconSize = 25;
            this.BtnCerrarSesion.IdleBorderColor = System.Drawing.Color.Gray;
            this.BtnCerrarSesion.IdleBorderRadius = 1;
            this.BtnCerrarSesion.IdleBorderThickness = 1;
            this.BtnCerrarSesion.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCerrarSesion.IdleIconLeftImage = null;
            this.BtnCerrarSesion.IdleIconRightImage = null;
            this.BtnCerrarSesion.IndicateFocus = false;
            this.BtnCerrarSesion.Location = new System.Drawing.Point(0, 572);
            this.BtnCerrarSesion.Name = "BtnCerrarSesion";
            this.BtnCerrarSesion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCerrarSesion.OnDisabledState.BorderRadius = 1;
            this.BtnCerrarSesion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCerrarSesion.OnDisabledState.BorderThickness = 1;
            this.BtnCerrarSesion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCerrarSesion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCerrarSesion.OnDisabledState.IconLeftImage = null;
            this.BtnCerrarSesion.OnDisabledState.IconRightImage = null;
            this.BtnCerrarSesion.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCerrarSesion.onHoverState.BorderRadius = 1;
            this.BtnCerrarSesion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCerrarSesion.onHoverState.BorderThickness = 1;
            this.BtnCerrarSesion.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCerrarSesion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCerrarSesion.onHoverState.IconLeftImage = null;
            this.BtnCerrarSesion.onHoverState.IconRightImage = null;
            this.BtnCerrarSesion.OnIdleState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCerrarSesion.OnIdleState.BorderRadius = 1;
            this.BtnCerrarSesion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCerrarSesion.OnIdleState.BorderThickness = 1;
            this.BtnCerrarSesion.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCerrarSesion.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCerrarSesion.OnIdleState.IconLeftImage = null;
            this.BtnCerrarSesion.OnIdleState.IconRightImage = null;
            this.BtnCerrarSesion.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCerrarSesion.OnPressedState.BorderRadius = 1;
            this.BtnCerrarSesion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCerrarSesion.OnPressedState.BorderThickness = 1;
            this.BtnCerrarSesion.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCerrarSesion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCerrarSesion.OnPressedState.IconLeftImage = null;
            this.BtnCerrarSesion.OnPressedState.IconRightImage = null;
            this.BtnCerrarSesion.Size = new System.Drawing.Size(233, 39);
            this.BtnCerrarSesion.TabIndex = 12;
            this.BtnCerrarSesion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCerrarSesion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCerrarSesion.TextMarginLeft = 0;
            this.BtnCerrarSesion.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCerrarSesion.UseDefaultRadiusAndThickness = true;
            this.BtnCerrarSesion.Click += new System.EventHandler(this.BtnCerrarSesion_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.bunifuPictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(233, 144);
            this.panel1.TabIndex = 1;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 69;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(45, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(139, 139);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 1;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // PanelContenedor
            // 
            this.PanelContenedor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PanelContenedor.Location = new System.Drawing.Point(233, 0);
            this.PanelContenedor.Name = "PanelContenedor";
            this.PanelContenedor.Size = new System.Drawing.Size(901, 611);
            this.PanelContenedor.TabIndex = 1;
            // 
            // FormMenuPrincipal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(1134, 611);
            this.Controls.Add(this.PanelContenedor);
            this.Controls.Add(this.PanelSideMenu);
            this.Name = "FormMenuPrincipal";
            this.Text = "Menú Principal";
            this.PanelSideMenu.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel PanelSideMenu;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCerrarSesion;
        private System.Windows.Forms.Panel PanelContenedor;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGestionUsuarios;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCobranza;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnRealizarReserva;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnInicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnAyuda;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCambiarPassword;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel5;
    }
}