namespace UI
{
    partial class FormGestionClientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionClientes));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.PanelData = new System.Windows.Forms.Panel();
            this.LblErrorContacto = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorApellido = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorMail = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorNombre = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorDireccion = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblErrorDni = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtContacto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblContacto = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblApellido = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblMail = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblNombre = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblDireccion = new Bunifu.UI.WinForms.BunifuLabel();
            this.TxtDni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblDni = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnModificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCrear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DataGridViewClientes = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.LblGestionClientes = new Bunifu.UI.WinForms.BunifuLabel();
            this.CheckShowDireccion = new System.Windows.Forms.CheckBox();
            this.PanelData.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewClientes)).BeginInit();
            this.SuspendLayout();
            // 
            // PanelData
            // 
            this.PanelData.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PanelData.Controls.Add(this.LblErrorContacto);
            this.PanelData.Controls.Add(this.LblErrorApellido);
            this.PanelData.Controls.Add(this.LblErrorMail);
            this.PanelData.Controls.Add(this.LblErrorNombre);
            this.PanelData.Controls.Add(this.LblErrorDireccion);
            this.PanelData.Controls.Add(this.LblErrorDni);
            this.PanelData.Controls.Add(this.TxtContacto);
            this.PanelData.Controls.Add(this.LblContacto);
            this.PanelData.Controls.Add(this.TxtApellido);
            this.PanelData.Controls.Add(this.LblApellido);
            this.PanelData.Controls.Add(this.TxtEmail);
            this.PanelData.Controls.Add(this.LblMail);
            this.PanelData.Controls.Add(this.TxtNombre);
            this.PanelData.Controls.Add(this.LblNombre);
            this.PanelData.Controls.Add(this.TxtDireccion);
            this.PanelData.Controls.Add(this.LblDireccion);
            this.PanelData.Controls.Add(this.TxtDni);
            this.PanelData.Controls.Add(this.LblDni);
            this.PanelData.Controls.Add(this.BtnCancelar);
            this.PanelData.Controls.Add(this.BtnGuardar);
            this.PanelData.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.PanelData.Location = new System.Drawing.Point(0, 313);
            this.PanelData.Name = "PanelData";
            this.PanelData.Size = new System.Drawing.Size(901, 298);
            this.PanelData.TabIndex = 36;
            // 
            // LblErrorContacto
            // 
            this.LblErrorContacto.AllowParentOverrides = false;
            this.LblErrorContacto.AutoEllipsis = false;
            this.LblErrorContacto.CursorType = null;
            this.LblErrorContacto.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorContacto.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorContacto.Location = new System.Drawing.Point(417, 273);
            this.LblErrorContacto.Name = "LblErrorContacto";
            this.LblErrorContacto.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorContacto.Size = new System.Drawing.Size(122, 15);
            this.LblErrorContacto.TabIndex = 50;
            this.LblErrorContacto.Text = "Debe Ingresar contacto";
            this.LblErrorContacto.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorContacto.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorContacto.Visible = false;
            // 
            // LblErrorApellido
            // 
            this.LblErrorApellido.AllowParentOverrides = false;
            this.LblErrorApellido.AutoEllipsis = false;
            this.LblErrorApellido.CursorType = null;
            this.LblErrorApellido.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorApellido.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorApellido.Location = new System.Drawing.Point(9, 272);
            this.LblErrorApellido.Name = "LblErrorApellido";
            this.LblErrorApellido.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorApellido.Size = new System.Drawing.Size(117, 15);
            this.LblErrorApellido.TabIndex = 49;
            this.LblErrorApellido.Text = "Debe Ingresar apellido";
            this.LblErrorApellido.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorApellido.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorApellido.Visible = false;
            // 
            // LblErrorMail
            // 
            this.LblErrorMail.AllowParentOverrides = false;
            this.LblErrorMail.AutoEllipsis = false;
            this.LblErrorMail.CursorType = null;
            this.LblErrorMail.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorMail.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorMail.Location = new System.Drawing.Point(417, 177);
            this.LblErrorMail.Name = "LblErrorMail";
            this.LblErrorMail.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorMail.Size = new System.Drawing.Size(104, 15);
            this.LblErrorMail.TabIndex = 48;
            this.LblErrorMail.Text = "Debe Ingresar email";
            this.LblErrorMail.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorMail.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorMail.Visible = false;
            // 
            // LblErrorNombre
            // 
            this.LblErrorNombre.AllowParentOverrides = false;
            this.LblErrorNombre.AutoEllipsis = false;
            this.LblErrorNombre.CursorType = null;
            this.LblErrorNombre.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorNombre.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorNombre.Location = new System.Drawing.Point(9, 177);
            this.LblErrorNombre.Name = "LblErrorNombre";
            this.LblErrorNombre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorNombre.Size = new System.Drawing.Size(117, 15);
            this.LblErrorNombre.TabIndex = 47;
            this.LblErrorNombre.Text = "Debe Ingresar nombre";
            this.LblErrorNombre.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorNombre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorNombre.Visible = false;
            // 
            // LblErrorDireccion
            // 
            this.LblErrorDireccion.AllowParentOverrides = false;
            this.LblErrorDireccion.AutoEllipsis = false;
            this.LblErrorDireccion.CursorType = null;
            this.LblErrorDireccion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorDireccion.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorDireccion.Location = new System.Drawing.Point(417, 80);
            this.LblErrorDireccion.Name = "LblErrorDireccion";
            this.LblErrorDireccion.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorDireccion.Size = new System.Drawing.Size(124, 15);
            this.LblErrorDireccion.TabIndex = 46;
            this.LblErrorDireccion.Text = "Debe ingresar dirección";
            this.LblErrorDireccion.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorDireccion.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorDireccion.Visible = false;
            // 
            // LblErrorDni
            // 
            this.LblErrorDni.AllowParentOverrides = false;
            this.LblErrorDni.AutoEllipsis = false;
            this.LblErrorDni.CursorType = null;
            this.LblErrorDni.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorDni.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorDni.Location = new System.Drawing.Point(9, 81);
            this.LblErrorDni.Name = "LblErrorDni";
            this.LblErrorDni.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorDni.Size = new System.Drawing.Size(92, 15);
            this.LblErrorDni.TabIndex = 45;
            this.LblErrorDni.Text = "Debe Ingresar dni";
            this.LblErrorDni.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorDni.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorDni.Visible = false;
            // 
            // TxtContacto
            // 
            this.TxtContacto.AcceptsReturn = false;
            this.TxtContacto.AcceptsTab = false;
            this.TxtContacto.AnimationSpeed = 200;
            this.TxtContacto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtContacto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtContacto.BackColor = System.Drawing.Color.Transparent;
            this.TxtContacto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtContacto.BackgroundImage")));
            this.TxtContacto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtContacto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtContacto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtContacto.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtContacto.BorderRadius = 1;
            this.TxtContacto.BorderThickness = 1;
            this.TxtContacto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtContacto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContacto.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtContacto.DefaultText = "";
            this.TxtContacto.FillColor = System.Drawing.Color.White;
            this.TxtContacto.HideSelection = true;
            this.TxtContacto.IconLeft = null;
            this.TxtContacto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContacto.IconPadding = 10;
            this.TxtContacto.IconRight = null;
            this.TxtContacto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtContacto.Lines = new string[0];
            this.TxtContacto.Location = new System.Drawing.Point(417, 229);
            this.TxtContacto.MaxLength = 32767;
            this.TxtContacto.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtContacto.Modified = false;
            this.TxtContacto.Multiline = false;
            this.TxtContacto.Name = "TxtContacto";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContacto.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtContacto.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContacto.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtContacto.OnIdleState = stateProperties28;
            this.TxtContacto.Padding = new System.Windows.Forms.Padding(3);
            this.TxtContacto.PasswordChar = '\0';
            this.TxtContacto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtContacto.PlaceholderText = "Ingrese Contacto";
            this.TxtContacto.ReadOnly = false;
            this.TxtContacto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtContacto.SelectedText = "";
            this.TxtContacto.SelectionLength = 0;
            this.TxtContacto.SelectionStart = 0;
            this.TxtContacto.ShortcutsEnabled = true;
            this.TxtContacto.Size = new System.Drawing.Size(260, 37);
            this.TxtContacto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtContacto.TabIndex = 44;
            this.TxtContacto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtContacto.TextMarginBottom = 0;
            this.TxtContacto.TextMarginLeft = 3;
            this.TxtContacto.TextMarginTop = 0;
            this.TxtContacto.TextPlaceholder = "Ingrese Contacto";
            this.TxtContacto.UseSystemPasswordChar = false;
            this.TxtContacto.WordWrap = true;
            // 
            // LblContacto
            // 
            this.LblContacto.AllowParentOverrides = false;
            this.LblContacto.AutoEllipsis = false;
            this.LblContacto.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblContacto.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblContacto.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblContacto.Location = new System.Drawing.Point(417, 200);
            this.LblContacto.Name = "LblContacto";
            this.LblContacto.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblContacto.Size = new System.Drawing.Size(65, 21);
            this.LblContacto.TabIndex = 43;
            this.LblContacto.Text = "Contacto:";
            this.LblContacto.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblContacto.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtApellido
            // 
            this.TxtApellido.AcceptsReturn = false;
            this.TxtApellido.AcceptsTab = false;
            this.TxtApellido.AnimationSpeed = 200;
            this.TxtApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtApellido.BackColor = System.Drawing.Color.Transparent;
            this.TxtApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtApellido.BackgroundImage")));
            this.TxtApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtApellido.BorderRadius = 1;
            this.TxtApellido.BorderThickness = 1;
            this.TxtApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtApellido.DefaultText = "";
            this.TxtApellido.FillColor = System.Drawing.Color.White;
            this.TxtApellido.HideSelection = true;
            this.TxtApellido.IconLeft = null;
            this.TxtApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.IconPadding = 10;
            this.TxtApellido.IconRight = null;
            this.TxtApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.Lines = new string[0];
            this.TxtApellido.Location = new System.Drawing.Point(9, 229);
            this.TxtApellido.MaxLength = 32767;
            this.TxtApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtApellido.Modified = false;
            this.TxtApellido.Multiline = false;
            this.TxtApellido.Name = "TxtApellido";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtApellido.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnIdleState = stateProperties32;
            this.TxtApellido.Padding = new System.Windows.Forms.Padding(3);
            this.TxtApellido.PasswordChar = '\0';
            this.TxtApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtApellido.PlaceholderText = "Ingrese Apellido";
            this.TxtApellido.ReadOnly = false;
            this.TxtApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtApellido.SelectedText = "";
            this.TxtApellido.SelectionLength = 0;
            this.TxtApellido.SelectionStart = 0;
            this.TxtApellido.ShortcutsEnabled = true;
            this.TxtApellido.Size = new System.Drawing.Size(260, 37);
            this.TxtApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtApellido.TabIndex = 42;
            this.TxtApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtApellido.TextMarginBottom = 0;
            this.TxtApellido.TextMarginLeft = 3;
            this.TxtApellido.TextMarginTop = 0;
            this.TxtApellido.TextPlaceholder = "Ingrese Apellido";
            this.TxtApellido.UseSystemPasswordChar = false;
            this.TxtApellido.WordWrap = true;
            // 
            // LblApellido
            // 
            this.LblApellido.AllowParentOverrides = false;
            this.LblApellido.AutoEllipsis = false;
            this.LblApellido.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblApellido.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblApellido.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblApellido.Location = new System.Drawing.Point(9, 200);
            this.LblApellido.Name = "LblApellido";
            this.LblApellido.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblApellido.Size = new System.Drawing.Size(60, 21);
            this.LblApellido.TabIndex = 41;
            this.LblApellido.Text = "Apellido:";
            this.LblApellido.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblApellido.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtEmail
            // 
            this.TxtEmail.AcceptsReturn = false;
            this.TxtEmail.AcceptsTab = false;
            this.TxtEmail.AnimationSpeed = 200;
            this.TxtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtEmail.BackColor = System.Drawing.Color.Transparent;
            this.TxtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtEmail.BackgroundImage")));
            this.TxtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtEmail.BorderRadius = 1;
            this.TxtEmail.BorderThickness = 1;
            this.TxtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtEmail.DefaultText = "";
            this.TxtEmail.FillColor = System.Drawing.Color.White;
            this.TxtEmail.HideSelection = true;
            this.TxtEmail.IconLeft = null;
            this.TxtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmail.IconPadding = 10;
            this.TxtEmail.IconRight = null;
            this.TxtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtEmail.Lines = new string[0];
            this.TxtEmail.Location = new System.Drawing.Point(417, 131);
            this.TxtEmail.MaxLength = 32767;
            this.TxtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtEmail.Modified = false;
            this.TxtEmail.Multiline = false;
            this.TxtEmail.Name = "TxtEmail";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmail.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtEmail.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmail.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtEmail.OnIdleState = stateProperties36;
            this.TxtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.TxtEmail.PasswordChar = '\0';
            this.TxtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtEmail.PlaceholderText = "Ingrese Email";
            this.TxtEmail.ReadOnly = false;
            this.TxtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtEmail.SelectedText = "";
            this.TxtEmail.SelectionLength = 0;
            this.TxtEmail.SelectionStart = 0;
            this.TxtEmail.ShortcutsEnabled = true;
            this.TxtEmail.Size = new System.Drawing.Size(260, 37);
            this.TxtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtEmail.TabIndex = 40;
            this.TxtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtEmail.TextMarginBottom = 0;
            this.TxtEmail.TextMarginLeft = 3;
            this.TxtEmail.TextMarginTop = 0;
            this.TxtEmail.TextPlaceholder = "Ingrese Email";
            this.TxtEmail.UseSystemPasswordChar = false;
            this.TxtEmail.WordWrap = true;
            // 
            // LblMail
            // 
            this.LblMail.AllowParentOverrides = false;
            this.LblMail.AutoEllipsis = false;
            this.LblMail.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblMail.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblMail.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblMail.Location = new System.Drawing.Point(417, 102);
            this.LblMail.Name = "LblMail";
            this.LblMail.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblMail.Size = new System.Drawing.Size(41, 21);
            this.LblMail.TabIndex = 39;
            this.LblMail.Text = "Email:";
            this.LblMail.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblMail.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtNombre
            // 
            this.TxtNombre.AcceptsReturn = false;
            this.TxtNombre.AcceptsTab = false;
            this.TxtNombre.AnimationSpeed = 200;
            this.TxtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombre.BackgroundImage")));
            this.TxtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombre.BorderRadius = 1;
            this.TxtNombre.BorderThickness = 1;
            this.TxtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombre.DefaultText = "";
            this.TxtNombre.FillColor = System.Drawing.Color.White;
            this.TxtNombre.HideSelection = true;
            this.TxtNombre.IconLeft = null;
            this.TxtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.IconPadding = 10;
            this.TxtNombre.IconRight = null;
            this.TxtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.Lines = new string[0];
            this.TxtNombre.Location = new System.Drawing.Point(9, 131);
            this.TxtNombre.MaxLength = 32767;
            this.TxtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombre.Modified = false;
            this.TxtNombre.Multiline = false;
            this.TxtNombre.Name = "TxtNombre";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombre.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnIdleState = stateProperties40;
            this.TxtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNombre.PasswordChar = '\0';
            this.TxtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombre.PlaceholderText = "Ingrese Nombre";
            this.TxtNombre.ReadOnly = false;
            this.TxtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombre.SelectedText = "";
            this.TxtNombre.SelectionLength = 0;
            this.TxtNombre.SelectionStart = 0;
            this.TxtNombre.ShortcutsEnabled = true;
            this.TxtNombre.Size = new System.Drawing.Size(260, 37);
            this.TxtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombre.TabIndex = 38;
            this.TxtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombre.TextMarginBottom = 0;
            this.TxtNombre.TextMarginLeft = 3;
            this.TxtNombre.TextMarginTop = 0;
            this.TxtNombre.TextPlaceholder = "Ingrese Nombre";
            this.TxtNombre.UseSystemPasswordChar = false;
            this.TxtNombre.WordWrap = true;
            // 
            // LblNombre
            // 
            this.LblNombre.AllowParentOverrides = false;
            this.LblNombre.AutoEllipsis = false;
            this.LblNombre.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblNombre.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblNombre.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblNombre.Location = new System.Drawing.Point(9, 102);
            this.LblNombre.Name = "LblNombre";
            this.LblNombre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblNombre.Size = new System.Drawing.Size(61, 21);
            this.LblNombre.TabIndex = 37;
            this.LblNombre.Text = "Nombre:";
            this.LblNombre.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblNombre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtDireccion
            // 
            this.TxtDireccion.AcceptsReturn = false;
            this.TxtDireccion.AcceptsTab = false;
            this.TxtDireccion.AnimationSpeed = 200;
            this.TxtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.TxtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDireccion.BackgroundImage")));
            this.TxtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDireccion.BorderRadius = 1;
            this.TxtDireccion.BorderThickness = 1;
            this.TxtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtDireccion.DefaultText = "";
            this.TxtDireccion.FillColor = System.Drawing.Color.White;
            this.TxtDireccion.HideSelection = true;
            this.TxtDireccion.IconLeft = null;
            this.TxtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.IconPadding = 10;
            this.TxtDireccion.IconRight = null;
            this.TxtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.Lines = new string[0];
            this.TxtDireccion.Location = new System.Drawing.Point(417, 36);
            this.TxtDireccion.MaxLength = 32767;
            this.TxtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDireccion.Modified = false;
            this.TxtDireccion.Multiline = false;
            this.TxtDireccion.Name = "TxtDireccion";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDireccion.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDireccion.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDireccion.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDireccion.OnIdleState = stateProperties44;
            this.TxtDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.TxtDireccion.PasswordChar = '\0';
            this.TxtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDireccion.PlaceholderText = "Ingrese Dirección";
            this.TxtDireccion.ReadOnly = false;
            this.TxtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtDireccion.SelectedText = "";
            this.TxtDireccion.SelectionLength = 0;
            this.TxtDireccion.SelectionStart = 0;
            this.TxtDireccion.ShortcutsEnabled = true;
            this.TxtDireccion.Size = new System.Drawing.Size(260, 37);
            this.TxtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtDireccion.TabIndex = 36;
            this.TxtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDireccion.TextMarginBottom = 0;
            this.TxtDireccion.TextMarginLeft = 3;
            this.TxtDireccion.TextMarginTop = 0;
            this.TxtDireccion.TextPlaceholder = "Ingrese Dirección";
            this.TxtDireccion.UseSystemPasswordChar = false;
            this.TxtDireccion.WordWrap = true;
            // 
            // LblDireccion
            // 
            this.LblDireccion.AllowParentOverrides = false;
            this.LblDireccion.AutoEllipsis = false;
            this.LblDireccion.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblDireccion.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblDireccion.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblDireccion.Location = new System.Drawing.Point(417, 6);
            this.LblDireccion.Name = "LblDireccion";
            this.LblDireccion.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblDireccion.Size = new System.Drawing.Size(68, 21);
            this.LblDireccion.TabIndex = 35;
            this.LblDireccion.Text = "Dirección:";
            this.LblDireccion.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblDireccion.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TxtDni
            // 
            this.TxtDni.AcceptsReturn = false;
            this.TxtDni.AcceptsTab = false;
            this.TxtDni.AnimationSpeed = 200;
            this.TxtDni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDni.BackColor = System.Drawing.Color.Transparent;
            this.TxtDni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDni.BackgroundImage")));
            this.TxtDni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtDni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtDni.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDni.BorderRadius = 1;
            this.TxtDni.BorderThickness = 1;
            this.TxtDni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtDni.DefaultText = "";
            this.TxtDni.FillColor = System.Drawing.Color.White;
            this.TxtDni.HideSelection = true;
            this.TxtDni.IconLeft = null;
            this.TxtDni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.IconPadding = 10;
            this.TxtDni.IconRight = null;
            this.TxtDni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.Lines = new string[0];
            this.TxtDni.Location = new System.Drawing.Point(9, 36);
            this.TxtDni.MaxLength = 32767;
            this.TxtDni.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDni.Modified = false;
            this.TxtDni.Multiline = false;
            this.TxtDni.Name = "TxtDni";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDni.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnIdleState = stateProperties48;
            this.TxtDni.Padding = new System.Windows.Forms.Padding(3);
            this.TxtDni.PasswordChar = '\0';
            this.TxtDni.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDni.PlaceholderText = "Ingrese Dni";
            this.TxtDni.ReadOnly = false;
            this.TxtDni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtDni.SelectedText = "";
            this.TxtDni.SelectionLength = 0;
            this.TxtDni.SelectionStart = 0;
            this.TxtDni.ShortcutsEnabled = true;
            this.TxtDni.Size = new System.Drawing.Size(260, 37);
            this.TxtDni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtDni.TabIndex = 34;
            this.TxtDni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDni.TextMarginBottom = 0;
            this.TxtDni.TextMarginLeft = 3;
            this.TxtDni.TextMarginTop = 0;
            this.TxtDni.TextPlaceholder = "Ingrese Dni";
            this.TxtDni.UseSystemPasswordChar = false;
            this.TxtDni.WordWrap = true;
            // 
            // LblDni
            // 
            this.LblDni.AllowParentOverrides = false;
            this.LblDni.AutoEllipsis = false;
            this.LblDni.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblDni.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblDni.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblDni.Location = new System.Drawing.Point(9, 6);
            this.LblDni.Name = "LblDni";
            this.LblDni.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblDni.Size = new System.Drawing.Size(27, 21);
            this.LblDni.TabIndex = 33;
            this.LblDni.Text = "Dni:";
            this.LblDni.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblDni.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnCancelar
            // 
            this.BtnCancelar.AllowAnimations = true;
            this.BtnCancelar.AllowMouseEffects = true;
            this.BtnCancelar.AllowToggling = false;
            this.BtnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCancelar.AnimationSpeed = 200;
            this.BtnCancelar.AutoGenerateColors = false;
            this.BtnCancelar.AutoRoundBorders = false;
            this.BtnCancelar.AutoSizeLeftIcon = true;
            this.BtnCancelar.AutoSizeRightIcon = true;
            this.BtnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancelar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancelar.BackgroundImage")));
            this.BtnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.ButtonText = "Cancelar";
            this.BtnCancelar.ButtonTextMarginLeft = 0;
            this.BtnCancelar.ColorContrastOnClick = 45;
            this.BtnCancelar.ColorContrastOnHover = 45;
            this.BtnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnCancelar.CustomizableEdges = borderEdges6;
            this.BtnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancelar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancelar.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancelar.IconMarginLeft = 11;
            this.BtnCancelar.IconPadding = 10;
            this.BtnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancelar.IconSize = 25;
            this.BtnCancelar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleBorderRadius = 1;
            this.BtnCancelar.IdleBorderThickness = 1;
            this.BtnCancelar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleIconLeftImage = null;
            this.BtnCancelar.IdleIconRightImage = null;
            this.BtnCancelar.IndicateFocus = false;
            this.BtnCancelar.Location = new System.Drawing.Point(738, 188);
            this.BtnCancelar.Name = "BtnCancelar";
            this.BtnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.OnDisabledState.BorderRadius = 1;
            this.BtnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnDisabledState.BorderThickness = 1;
            this.BtnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.OnDisabledState.IconLeftImage = null;
            this.BtnCancelar.OnDisabledState.IconRightImage = null;
            this.BtnCancelar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.BorderRadius = 1;
            this.BtnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.onHoverState.BorderThickness = 1;
            this.BtnCancelar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.onHoverState.IconLeftImage = null;
            this.BtnCancelar.onHoverState.IconRightImage = null;
            this.BtnCancelar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.BorderRadius = 1;
            this.BtnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnIdleState.BorderThickness = 1;
            this.BtnCancelar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.IconLeftImage = null;
            this.BtnCancelar.OnIdleState.IconRightImage = null;
            this.BtnCancelar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCancelar.OnPressedState.BorderRadius = 1;
            this.BtnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnPressedState.BorderThickness = 1;
            this.BtnCancelar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.IconLeftImage = null;
            this.BtnCancelar.OnPressedState.IconRightImage = null;
            this.BtnCancelar.Size = new System.Drawing.Size(150, 39);
            this.BtnCancelar.TabIndex = 22;
            this.BtnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancelar.TextMarginLeft = 0;
            this.BtnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancelar.UseDefaultRadiusAndThickness = true;
            this.BtnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // BtnGuardar
            // 
            this.BtnGuardar.AllowAnimations = true;
            this.BtnGuardar.AllowMouseEffects = true;
            this.BtnGuardar.AllowToggling = false;
            this.BtnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnGuardar.AnimationSpeed = 200;
            this.BtnGuardar.AutoGenerateColors = false;
            this.BtnGuardar.AutoRoundBorders = false;
            this.BtnGuardar.AutoSizeLeftIcon = true;
            this.BtnGuardar.AutoSizeRightIcon = true;
            this.BtnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.BtnGuardar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGuardar.BackgroundImage")));
            this.BtnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.ButtonText = "Guardar";
            this.BtnGuardar.ButtonTextMarginLeft = 0;
            this.BtnGuardar.ColorContrastOnClick = 45;
            this.BtnGuardar.ColorContrastOnHover = 45;
            this.BtnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnGuardar.CustomizableEdges = borderEdges7;
            this.BtnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGuardar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnGuardar.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGuardar.IconMarginLeft = 11;
            this.BtnGuardar.IconPadding = 10;
            this.BtnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGuardar.IconSize = 25;
            this.BtnGuardar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleBorderRadius = 1;
            this.BtnGuardar.IdleBorderThickness = 1;
            this.BtnGuardar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleIconLeftImage = null;
            this.BtnGuardar.IdleIconRightImage = null;
            this.BtnGuardar.IndicateFocus = false;
            this.BtnGuardar.Location = new System.Drawing.Point(738, 97);
            this.BtnGuardar.Name = "BtnGuardar";
            this.BtnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.OnDisabledState.BorderRadius = 1;
            this.BtnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnDisabledState.BorderThickness = 1;
            this.BtnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.OnDisabledState.IconLeftImage = null;
            this.BtnGuardar.OnDisabledState.IconRightImage = null;
            this.BtnGuardar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.BorderRadius = 1;
            this.BtnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.onHoverState.BorderThickness = 1;
            this.BtnGuardar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.onHoverState.IconLeftImage = null;
            this.BtnGuardar.onHoverState.IconRightImage = null;
            this.BtnGuardar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.BorderRadius = 1;
            this.BtnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnIdleState.BorderThickness = 1;
            this.BtnGuardar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnIdleState.IconLeftImage = null;
            this.BtnGuardar.OnIdleState.IconRightImage = null;
            this.BtnGuardar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGuardar.OnPressedState.BorderRadius = 1;
            this.BtnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnPressedState.BorderThickness = 1;
            this.BtnGuardar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnPressedState.IconLeftImage = null;
            this.BtnGuardar.OnPressedState.IconRightImage = null;
            this.BtnGuardar.Size = new System.Drawing.Size(150, 39);
            this.BtnGuardar.TabIndex = 21;
            this.BtnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGuardar.TextMarginLeft = 0;
            this.BtnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGuardar.UseDefaultRadiusAndThickness = true;
            this.BtnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // BtnEliminar
            // 
            this.BtnEliminar.AllowAnimations = true;
            this.BtnEliminar.AllowMouseEffects = true;
            this.BtnEliminar.AllowToggling = false;
            this.BtnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnEliminar.AnimationSpeed = 200;
            this.BtnEliminar.AutoGenerateColors = false;
            this.BtnEliminar.AutoRoundBorders = false;
            this.BtnEliminar.AutoSizeLeftIcon = true;
            this.BtnEliminar.AutoSizeRightIcon = true;
            this.BtnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.BtnEliminar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEliminar.BackgroundImage")));
            this.BtnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.ButtonText = "Eliminar";
            this.BtnEliminar.ButtonTextMarginLeft = 0;
            this.BtnEliminar.ColorContrastOnClick = 45;
            this.BtnEliminar.ColorContrastOnHover = 45;
            this.BtnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.BtnEliminar.CustomizableEdges = borderEdges8;
            this.BtnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnEliminar.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEliminar.IconMarginLeft = 11;
            this.BtnEliminar.IconPadding = 10;
            this.BtnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEliminar.IconSize = 25;
            this.BtnEliminar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleBorderRadius = 1;
            this.BtnEliminar.IdleBorderThickness = 1;
            this.BtnEliminar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleIconLeftImage = null;
            this.BtnEliminar.IdleIconRightImage = null;
            this.BtnEliminar.IndicateFocus = false;
            this.BtnEliminar.Location = new System.Drawing.Point(738, 254);
            this.BtnEliminar.Name = "BtnEliminar";
            this.BtnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.OnDisabledState.BorderRadius = 1;
            this.BtnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnDisabledState.BorderThickness = 1;
            this.BtnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.OnDisabledState.IconLeftImage = null;
            this.BtnEliminar.OnDisabledState.IconRightImage = null;
            this.BtnEliminar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.BorderRadius = 1;
            this.BtnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.onHoverState.BorderThickness = 1;
            this.BtnEliminar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.onHoverState.IconLeftImage = null;
            this.BtnEliminar.onHoverState.IconRightImage = null;
            this.BtnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.BorderRadius = 1;
            this.BtnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnIdleState.BorderThickness = 1;
            this.BtnEliminar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnIdleState.IconLeftImage = null;
            this.BtnEliminar.OnIdleState.IconRightImage = null;
            this.BtnEliminar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnEliminar.OnPressedState.BorderRadius = 1;
            this.BtnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnPressedState.BorderThickness = 1;
            this.BtnEliminar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnPressedState.IconLeftImage = null;
            this.BtnEliminar.OnPressedState.IconRightImage = null;
            this.BtnEliminar.Size = new System.Drawing.Size(150, 39);
            this.BtnEliminar.TabIndex = 35;
            this.BtnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEliminar.TextMarginLeft = 0;
            this.BtnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEliminar.UseDefaultRadiusAndThickness = true;
            this.BtnEliminar.Click += new System.EventHandler(this.BtnEliminar_Click);
            // 
            // BtnModificar
            // 
            this.BtnModificar.AllowAnimations = true;
            this.BtnModificar.AllowMouseEffects = true;
            this.BtnModificar.AllowToggling = false;
            this.BtnModificar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnModificar.AnimationSpeed = 200;
            this.BtnModificar.AutoGenerateColors = false;
            this.BtnModificar.AutoRoundBorders = false;
            this.BtnModificar.AutoSizeLeftIcon = true;
            this.BtnModificar.AutoSizeRightIcon = true;
            this.BtnModificar.BackColor = System.Drawing.Color.Transparent;
            this.BtnModificar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnModificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnModificar.BackgroundImage")));
            this.BtnModificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.ButtonText = "Modificar";
            this.BtnModificar.ButtonTextMarginLeft = 0;
            this.BtnModificar.ColorContrastOnClick = 45;
            this.BtnModificar.ColorContrastOnHover = 45;
            this.BtnModificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.BtnModificar.CustomizableEdges = borderEdges9;
            this.BtnModificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnModificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnModificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnModificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnModificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnModificar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnModificar.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnModificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnModificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnModificar.IconMarginLeft = 11;
            this.BtnModificar.IconPadding = 10;
            this.BtnModificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnModificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnModificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnModificar.IconSize = 25;
            this.BtnModificar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnModificar.IdleBorderRadius = 1;
            this.BtnModificar.IdleBorderThickness = 1;
            this.BtnModificar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.IdleIconLeftImage = null;
            this.BtnModificar.IdleIconRightImage = null;
            this.BtnModificar.IndicateFocus = false;
            this.BtnModificar.Location = new System.Drawing.Point(738, 174);
            this.BtnModificar.Name = "BtnModificar";
            this.BtnModificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnModificar.OnDisabledState.BorderRadius = 1;
            this.BtnModificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnDisabledState.BorderThickness = 1;
            this.BtnModificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnModificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnModificar.OnDisabledState.IconLeftImage = null;
            this.BtnModificar.OnDisabledState.IconRightImage = null;
            this.BtnModificar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnModificar.onHoverState.BorderRadius = 1;
            this.BtnModificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.onHoverState.BorderThickness = 1;
            this.BtnModificar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnModificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.onHoverState.IconLeftImage = null;
            this.BtnModificar.onHoverState.IconRightImage = null;
            this.BtnModificar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnIdleState.BorderRadius = 1;
            this.BtnModificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnIdleState.BorderThickness = 1;
            this.BtnModificar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.OnIdleState.IconLeftImage = null;
            this.BtnModificar.OnIdleState.IconRightImage = null;
            this.BtnModificar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnModificar.OnPressedState.BorderRadius = 1;
            this.BtnModificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnModificar.OnPressedState.BorderThickness = 1;
            this.BtnModificar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnModificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnModificar.OnPressedState.IconLeftImage = null;
            this.BtnModificar.OnPressedState.IconRightImage = null;
            this.BtnModificar.Size = new System.Drawing.Size(150, 39);
            this.BtnModificar.TabIndex = 34;
            this.BtnModificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnModificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnModificar.TextMarginLeft = 0;
            this.BtnModificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnModificar.UseDefaultRadiusAndThickness = true;
            this.BtnModificar.Click += new System.EventHandler(this.BtnModificar_Click);
            // 
            // BtnCrear
            // 
            this.BtnCrear.AllowAnimations = true;
            this.BtnCrear.AllowMouseEffects = true;
            this.BtnCrear.AllowToggling = false;
            this.BtnCrear.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCrear.AnimationSpeed = 200;
            this.BtnCrear.AutoGenerateColors = false;
            this.BtnCrear.AutoRoundBorders = false;
            this.BtnCrear.AutoSizeLeftIcon = true;
            this.BtnCrear.AutoSizeRightIcon = true;
            this.BtnCrear.BackColor = System.Drawing.Color.Transparent;
            this.BtnCrear.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCrear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCrear.BackgroundImage")));
            this.BtnCrear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.ButtonText = "Crear";
            this.BtnCrear.ButtonTextMarginLeft = 0;
            this.BtnCrear.ColorContrastOnClick = 45;
            this.BtnCrear.ColorContrastOnHover = 45;
            this.BtnCrear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.BtnCrear.CustomizableEdges = borderEdges10;
            this.BtnCrear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCrear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCrear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCrear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCrear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCrear.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCrear.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCrear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCrear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCrear.IconMarginLeft = 11;
            this.BtnCrear.IconPadding = 10;
            this.BtnCrear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCrear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCrear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCrear.IconSize = 25;
            this.BtnCrear.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCrear.IdleBorderRadius = 1;
            this.BtnCrear.IdleBorderThickness = 1;
            this.BtnCrear.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.IdleIconLeftImage = null;
            this.BtnCrear.IdleIconRightImage = null;
            this.BtnCrear.IndicateFocus = false;
            this.BtnCrear.Location = new System.Drawing.Point(738, 92);
            this.BtnCrear.Name = "BtnCrear";
            this.BtnCrear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCrear.OnDisabledState.BorderRadius = 1;
            this.BtnCrear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnDisabledState.BorderThickness = 1;
            this.BtnCrear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCrear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCrear.OnDisabledState.IconLeftImage = null;
            this.BtnCrear.OnDisabledState.IconRightImage = null;
            this.BtnCrear.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCrear.onHoverState.BorderRadius = 1;
            this.BtnCrear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.onHoverState.BorderThickness = 1;
            this.BtnCrear.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCrear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.onHoverState.IconLeftImage = null;
            this.BtnCrear.onHoverState.IconRightImage = null;
            this.BtnCrear.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnIdleState.BorderRadius = 1;
            this.BtnCrear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnIdleState.BorderThickness = 1;
            this.BtnCrear.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.OnIdleState.IconLeftImage = null;
            this.BtnCrear.OnIdleState.IconRightImage = null;
            this.BtnCrear.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCrear.OnPressedState.BorderRadius = 1;
            this.BtnCrear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCrear.OnPressedState.BorderThickness = 1;
            this.BtnCrear.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCrear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCrear.OnPressedState.IconLeftImage = null;
            this.BtnCrear.OnPressedState.IconRightImage = null;
            this.BtnCrear.Size = new System.Drawing.Size(150, 39);
            this.BtnCrear.TabIndex = 33;
            this.BtnCrear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCrear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCrear.TextMarginLeft = 0;
            this.BtnCrear.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCrear.UseDefaultRadiusAndThickness = true;
            this.BtnCrear.Click += new System.EventHandler(this.BtnCrear_Click);
            // 
            // DataGridViewClientes
            // 
            this.DataGridViewClientes.AllowCustomTheming = false;
            this.DataGridViewClientes.AllowUserToAddRows = false;
            this.DataGridViewClientes.AllowUserToDeleteRows = false;
            this.DataGridViewClientes.AllowUserToResizeColumns = false;
            this.DataGridViewClientes.AllowUserToResizeRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewClientes.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.DataGridViewClientes.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.DataGridViewClientes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DataGridViewClientes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DataGridViewClientes.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DataGridViewClientes.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DataGridViewClientes.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.DataGridViewClientes.ColumnHeadersHeight = 40;
            this.DataGridViewClientes.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.DataGridViewClientes.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewClientes.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewClientes.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DataGridViewClientes.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DataGridViewClientes.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.DataGridViewClientes.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DataGridViewClientes.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.DataGridViewClientes.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewClientes.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DataGridViewClientes.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.DataGridViewClientes.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DataGridViewClientes.CurrentTheme.Name = null;
            this.DataGridViewClientes.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.DataGridViewClientes.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DataGridViewClientes.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DataGridViewClientes.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DataGridViewClientes.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DataGridViewClientes.DefaultCellStyle = dataGridViewCellStyle6;
            this.DataGridViewClientes.EnableHeadersVisualStyles = false;
            this.DataGridViewClientes.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DataGridViewClientes.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.DataGridViewClientes.HeaderBgColor = System.Drawing.Color.Empty;
            this.DataGridViewClientes.HeaderForeColor = System.Drawing.Color.White;
            this.DataGridViewClientes.Location = new System.Drawing.Point(11, 92);
            this.DataGridViewClientes.MultiSelect = false;
            this.DataGridViewClientes.Name = "DataGridViewClientes";
            this.DataGridViewClientes.ReadOnly = true;
            this.DataGridViewClientes.RowHeadersVisible = false;
            this.DataGridViewClientes.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DataGridViewClientes.RowTemplate.Height = 40;
            this.DataGridViewClientes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DataGridViewClientes.ShowCellErrors = false;
            this.DataGridViewClientes.ShowCellToolTips = false;
            this.DataGridViewClientes.ShowEditingIcon = false;
            this.DataGridViewClientes.ShowRowErrors = false;
            this.DataGridViewClientes.Size = new System.Drawing.Size(708, 201);
            this.DataGridViewClientes.TabIndex = 32;
            this.DataGridViewClientes.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.DataGridViewClientes.DataBindingComplete += new System.Windows.Forms.DataGridViewBindingCompleteEventHandler(this.DataGridViewClientes_DataBindingComplete);
            // 
            // LblGestionClientes
            // 
            this.LblGestionClientes.AllowParentOverrides = false;
            this.LblGestionClientes.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.LblGestionClientes.AutoEllipsis = false;
            this.LblGestionClientes.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblGestionClientes.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblGestionClientes.Font = new System.Drawing.Font("Segoe UI", 20.25F);
            this.LblGestionClientes.Location = new System.Drawing.Point(11, 26);
            this.LblGestionClientes.Name = "LblGestionClientes";
            this.LblGestionClientes.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblGestionClientes.Size = new System.Drawing.Size(274, 45);
            this.LblGestionClientes.TabIndex = 31;
            this.LblGestionClientes.Text = "Gestión de clientes";
            this.LblGestionClientes.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblGestionClientes.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // CheckShowDireccion
            // 
            this.CheckShowDireccion.AutoSize = true;
            this.CheckShowDireccion.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CheckShowDireccion.Location = new System.Drawing.Point(556, 50);
            this.CheckShowDireccion.Name = "CheckShowDireccion";
            this.CheckShowDireccion.Size = new System.Drawing.Size(162, 21);
            this.CheckShowDireccion.TabIndex = 37;
            this.CheckShowDireccion.Text = "Ver direccion clientes";
            this.CheckShowDireccion.UseVisualStyleBackColor = true;
            this.CheckShowDireccion.CheckedChanged += new System.EventHandler(this.CheckShowDireccion_CheckedChanged);
            // 
            // FormGestionClientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(901, 611);
            this.Controls.Add(this.CheckShowDireccion);
            this.Controls.Add(this.PanelData);
            this.Controls.Add(this.BtnEliminar);
            this.Controls.Add(this.BtnModificar);
            this.Controls.Add(this.BtnCrear);
            this.Controls.Add(this.DataGridViewClientes);
            this.Controls.Add(this.LblGestionClientes);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormGestionClientes";
            this.Text = "FormGestionClientes";
            this.PanelData.ResumeLayout(false);
            this.PanelData.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewClientes)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel PanelData;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancelar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnModificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCrear;
        private Bunifu.UI.WinForms.BunifuDataGridView DataGridViewClientes;
        private Bunifu.UI.WinForms.BunifuLabel LblGestionClientes;
        private System.Windows.Forms.CheckBox CheckShowDireccion;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorContacto;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorApellido;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorMail;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorNombre;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorDireccion;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorDni;
        private Bunifu.UI.WinForms.BunifuTextBox TxtContacto;
        private Bunifu.UI.WinForms.BunifuLabel LblContacto;
        private Bunifu.UI.WinForms.BunifuTextBox TxtApellido;
        private Bunifu.UI.WinForms.BunifuLabel LblApellido;
        private Bunifu.UI.WinForms.BunifuTextBox TxtEmail;
        private Bunifu.UI.WinForms.BunifuLabel LblMail;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombre;
        private Bunifu.UI.WinForms.BunifuLabel LblNombre;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDireccion;
        private Bunifu.UI.WinForms.BunifuLabel LblDireccion;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDni;
        private Bunifu.UI.WinForms.BunifuLabel LblDni;
    }
}