namespace UI
{
    partial class FormGestionFamiliaPermisos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionFamiliaPermisos));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.BtnNuevaFamilia = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CmbFamilias = new System.Windows.Forms.ComboBox();
            this.LblUsuariosBloqueados = new Bunifu.UI.WinForms.BunifuLabel();
            this.PanelData = new System.Windows.Forms.Panel();
            this.LblErrorNombreFamilia = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnAgregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSacar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ListBoxFamilias = new System.Windows.Forms.ListBox();
            this.ListBoxPermisos = new System.Windows.Forms.ListBox();
            this.TxtNombreFamilia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ListBoxPermisosFamilia = new System.Windows.Forms.ListBox();
            this.BtnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnNuevoPerfil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PanelData.SuspendLayout();
            this.SuspendLayout();
            // 
            // BtnNuevaFamilia
            // 
            this.BtnNuevaFamilia.AllowAnimations = true;
            this.BtnNuevaFamilia.AllowMouseEffects = true;
            this.BtnNuevaFamilia.AllowToggling = false;
            this.BtnNuevaFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnNuevaFamilia.AnimationSpeed = 200;
            this.BtnNuevaFamilia.AutoGenerateColors = false;
            this.BtnNuevaFamilia.AutoRoundBorders = false;
            this.BtnNuevaFamilia.AutoSizeLeftIcon = true;
            this.BtnNuevaFamilia.AutoSizeRightIcon = true;
            this.BtnNuevaFamilia.BackColor = System.Drawing.Color.Transparent;
            this.BtnNuevaFamilia.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnNuevaFamilia.BackgroundImage")));
            this.BtnNuevaFamilia.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.ButtonText = "Nueva Familia de Permisos";
            this.BtnNuevaFamilia.ButtonTextMarginLeft = 0;
            this.BtnNuevaFamilia.ColorContrastOnClick = 45;
            this.BtnNuevaFamilia.ColorContrastOnHover = 45;
            this.BtnNuevaFamilia.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnNuevaFamilia.CustomizableEdges = borderEdges1;
            this.BtnNuevaFamilia.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnNuevaFamilia.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevaFamilia.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevaFamilia.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevaFamilia.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnNuevaFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnNuevaFamilia.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnNuevaFamilia.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevaFamilia.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnNuevaFamilia.IconMarginLeft = 11;
            this.BtnNuevaFamilia.IconPadding = 10;
            this.BtnNuevaFamilia.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnNuevaFamilia.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevaFamilia.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnNuevaFamilia.IconSize = 25;
            this.BtnNuevaFamilia.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.IdleBorderRadius = 1;
            this.BtnNuevaFamilia.IdleBorderThickness = 1;
            this.BtnNuevaFamilia.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.IdleIconLeftImage = null;
            this.BtnNuevaFamilia.IdleIconRightImage = null;
            this.BtnNuevaFamilia.IndicateFocus = false;
            this.BtnNuevaFamilia.Location = new System.Drawing.Point(343, 67);
            this.BtnNuevaFamilia.Name = "BtnNuevaFamilia";
            this.BtnNuevaFamilia.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevaFamilia.OnDisabledState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnDisabledState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevaFamilia.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevaFamilia.OnDisabledState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnDisabledState.IconRightImage = null;
            this.BtnNuevaFamilia.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnNuevaFamilia.onHoverState.BorderRadius = 1;
            this.BtnNuevaFamilia.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.onHoverState.BorderThickness = 1;
            this.BtnNuevaFamilia.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnNuevaFamilia.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.onHoverState.IconLeftImage = null;
            this.BtnNuevaFamilia.onHoverState.IconRightImage = null;
            this.BtnNuevaFamilia.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnIdleState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnIdleState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.OnIdleState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnIdleState.IconRightImage = null;
            this.BtnNuevaFamilia.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnNuevaFamilia.OnPressedState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnPressedState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.OnPressedState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnPressedState.IconRightImage = null;
            this.BtnNuevaFamilia.Size = new System.Drawing.Size(175, 21);
            this.BtnNuevaFamilia.TabIndex = 40;
            this.BtnNuevaFamilia.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnNuevaFamilia.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnNuevaFamilia.TextMarginLeft = 0;
            this.BtnNuevaFamilia.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnNuevaFamilia.UseDefaultRadiusAndThickness = true;
            this.BtnNuevaFamilia.Click += new System.EventHandler(this.BtnNuevaFamilia_Click);
            // 
            // CmbFamilias
            // 
            this.CmbFamilias.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbFamilias.FormattingEnabled = true;
            this.CmbFamilias.Location = new System.Drawing.Point(167, 67);
            this.CmbFamilias.Name = "CmbFamilias";
            this.CmbFamilias.Size = new System.Drawing.Size(158, 21);
            this.CmbFamilias.TabIndex = 39;
            this.CmbFamilias.SelectionChangeCommitted += new System.EventHandler(this.CmbFamilias_SelectionChangeCommitted);
            // 
            // LblUsuariosBloqueados
            // 
            this.LblUsuariosBloqueados.AllowParentOverrides = false;
            this.LblUsuariosBloqueados.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblUsuariosBloqueados.AutoEllipsis = false;
            this.LblUsuariosBloqueados.CursorType = null;
            this.LblUsuariosBloqueados.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblUsuariosBloqueados.Location = new System.Drawing.Point(12, 67);
            this.LblUsuariosBloqueados.Name = "LblUsuariosBloqueados";
            this.LblUsuariosBloqueados.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblUsuariosBloqueados.Size = new System.Drawing.Size(149, 21);
            this.LblUsuariosBloqueados.TabIndex = 38;
            this.LblUsuariosBloqueados.Text = "Familias de permisos:";
            this.LblUsuariosBloqueados.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblUsuariosBloqueados.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PanelData
            // 
            this.PanelData.Controls.Add(this.LblErrorNombreFamilia);
            this.PanelData.Controls.Add(this.BtnAgregar);
            this.PanelData.Controls.Add(this.BtnSacar);
            this.PanelData.Controls.Add(this.bunifuLabel5);
            this.PanelData.Controls.Add(this.bunifuLabel4);
            this.PanelData.Controls.Add(this.bunifuLabel3);
            this.PanelData.Controls.Add(this.ListBoxFamilias);
            this.PanelData.Controls.Add(this.ListBoxPermisos);
            this.PanelData.Controls.Add(this.TxtNombreFamilia);
            this.PanelData.Controls.Add(this.bunifuLabel2);
            this.PanelData.Controls.Add(this.ListBoxPermisosFamilia);
            this.PanelData.Controls.Add(this.BtnCancelar);
            this.PanelData.Controls.Add(this.BtnGuardar);
            this.PanelData.Location = new System.Drawing.Point(2, 110);
            this.PanelData.Name = "PanelData";
            this.PanelData.Size = new System.Drawing.Size(897, 489);
            this.PanelData.TabIndex = 37;
            // 
            // LblErrorNombreFamilia
            // 
            this.LblErrorNombreFamilia.AllowParentOverrides = false;
            this.LblErrorNombreFamilia.AutoEllipsis = false;
            this.LblErrorNombreFamilia.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblErrorNombreFamilia.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblErrorNombreFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorNombreFamilia.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorNombreFamilia.Location = new System.Drawing.Point(346, 13);
            this.LblErrorNombreFamilia.Name = "LblErrorNombreFamilia";
            this.LblErrorNombreFamilia.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorNombreFamilia.Size = new System.Drawing.Size(172, 15);
            this.LblErrorNombreFamilia.TabIndex = 54;
            this.LblErrorNombreFamilia.Text = "Debe ingresar nombre de familia";
            this.LblErrorNombreFamilia.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorNombreFamilia.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorNombreFamilia.Visible = false;
            // 
            // BtnAgregar
            // 
            this.BtnAgregar.AllowAnimations = true;
            this.BtnAgregar.AllowMouseEffects = true;
            this.BtnAgregar.AllowToggling = false;
            this.BtnAgregar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnAgregar.AnimationSpeed = 200;
            this.BtnAgregar.AutoGenerateColors = false;
            this.BtnAgregar.AutoRoundBorders = false;
            this.BtnAgregar.AutoSizeLeftIcon = true;
            this.BtnAgregar.AutoSizeRightIcon = true;
            this.BtnAgregar.BackColor = System.Drawing.Color.Transparent;
            this.BtnAgregar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnAgregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAgregar.BackgroundImage")));
            this.BtnAgregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregar.ButtonText = "<=";
            this.BtnAgregar.ButtonTextMarginLeft = 0;
            this.BtnAgregar.ColorContrastOnClick = 45;
            this.BtnAgregar.ColorContrastOnHover = 45;
            this.BtnAgregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnAgregar.CustomizableEdges = borderEdges2;
            this.BtnAgregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAgregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAgregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAgregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAgregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnAgregar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnAgregar.ForeColor = System.Drawing.Color.White;
            this.BtnAgregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAgregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAgregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAgregar.IconMarginLeft = 11;
            this.BtnAgregar.IconPadding = 10;
            this.BtnAgregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAgregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAgregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAgregar.IconSize = 25;
            this.BtnAgregar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnAgregar.IdleBorderRadius = 1;
            this.BtnAgregar.IdleBorderThickness = 1;
            this.BtnAgregar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnAgregar.IdleIconLeftImage = null;
            this.BtnAgregar.IdleIconRightImage = null;
            this.BtnAgregar.IndicateFocus = false;
            this.BtnAgregar.Location = new System.Drawing.Point(432, 240);
            this.BtnAgregar.Name = "BtnAgregar";
            this.BtnAgregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAgregar.OnDisabledState.BorderRadius = 1;
            this.BtnAgregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregar.OnDisabledState.BorderThickness = 1;
            this.BtnAgregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAgregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAgregar.OnDisabledState.IconLeftImage = null;
            this.BtnAgregar.OnDisabledState.IconRightImage = null;
            this.BtnAgregar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnAgregar.onHoverState.BorderRadius = 1;
            this.BtnAgregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregar.onHoverState.BorderThickness = 1;
            this.BtnAgregar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnAgregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregar.onHoverState.IconLeftImage = null;
            this.BtnAgregar.onHoverState.IconRightImage = null;
            this.BtnAgregar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnAgregar.OnIdleState.BorderRadius = 1;
            this.BtnAgregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregar.OnIdleState.BorderThickness = 1;
            this.BtnAgregar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAgregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregar.OnIdleState.IconLeftImage = null;
            this.BtnAgregar.OnIdleState.IconRightImage = null;
            this.BtnAgregar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnAgregar.OnPressedState.BorderRadius = 1;
            this.BtnAgregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregar.OnPressedState.BorderThickness = 1;
            this.BtnAgregar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAgregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregar.OnPressedState.IconLeftImage = null;
            this.BtnAgregar.OnPressedState.IconRightImage = null;
            this.BtnAgregar.Size = new System.Drawing.Size(63, 34);
            this.BtnAgregar.TabIndex = 53;
            this.BtnAgregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnAgregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAgregar.TextMarginLeft = 0;
            this.BtnAgregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnAgregar.UseDefaultRadiusAndThickness = true;
            this.BtnAgregar.Click += new System.EventHandler(this.BtnAgregar_Click);
            // 
            // BtnSacar
            // 
            this.BtnSacar.AllowAnimations = true;
            this.BtnSacar.AllowMouseEffects = true;
            this.BtnSacar.AllowToggling = false;
            this.BtnSacar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnSacar.AnimationSpeed = 200;
            this.BtnSacar.AutoGenerateColors = false;
            this.BtnSacar.AutoRoundBorders = false;
            this.BtnSacar.AutoSizeLeftIcon = true;
            this.BtnSacar.AutoSizeRightIcon = true;
            this.BtnSacar.BackColor = System.Drawing.Color.Transparent;
            this.BtnSacar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnSacar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSacar.BackgroundImage")));
            this.BtnSacar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacar.ButtonText = "=>";
            this.BtnSacar.ButtonTextMarginLeft = 0;
            this.BtnSacar.ColorContrastOnClick = 45;
            this.BtnSacar.ColorContrastOnHover = 45;
            this.BtnSacar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnSacar.CustomizableEdges = borderEdges3;
            this.BtnSacar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSacar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSacar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSacar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSacar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSacar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSacar.ForeColor = System.Drawing.Color.White;
            this.BtnSacar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSacar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSacar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSacar.IconMarginLeft = 11;
            this.BtnSacar.IconPadding = 10;
            this.BtnSacar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSacar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSacar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSacar.IconSize = 25;
            this.BtnSacar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnSacar.IdleBorderRadius = 1;
            this.BtnSacar.IdleBorderThickness = 1;
            this.BtnSacar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnSacar.IdleIconLeftImage = null;
            this.BtnSacar.IdleIconRightImage = null;
            this.BtnSacar.IndicateFocus = false;
            this.BtnSacar.Location = new System.Drawing.Point(432, 186);
            this.BtnSacar.Name = "BtnSacar";
            this.BtnSacar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSacar.OnDisabledState.BorderRadius = 1;
            this.BtnSacar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacar.OnDisabledState.BorderThickness = 1;
            this.BtnSacar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSacar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSacar.OnDisabledState.IconLeftImage = null;
            this.BtnSacar.OnDisabledState.IconRightImage = null;
            this.BtnSacar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnSacar.onHoverState.BorderRadius = 1;
            this.BtnSacar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacar.onHoverState.BorderThickness = 1;
            this.BtnSacar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnSacar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSacar.onHoverState.IconLeftImage = null;
            this.BtnSacar.onHoverState.IconRightImage = null;
            this.BtnSacar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnSacar.OnIdleState.BorderRadius = 1;
            this.BtnSacar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacar.OnIdleState.BorderThickness = 1;
            this.BtnSacar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnSacar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSacar.OnIdleState.IconLeftImage = null;
            this.BtnSacar.OnIdleState.IconRightImage = null;
            this.BtnSacar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnSacar.OnPressedState.BorderRadius = 1;
            this.BtnSacar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacar.OnPressedState.BorderThickness = 1;
            this.BtnSacar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnSacar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSacar.OnPressedState.IconLeftImage = null;
            this.BtnSacar.OnPressedState.IconRightImage = null;
            this.BtnSacar.Size = new System.Drawing.Size(63, 34);
            this.BtnSacar.TabIndex = 52;
            this.BtnSacar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSacar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSacar.TextMarginLeft = 0;
            this.BtnSacar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnSacar.UseDefaultRadiusAndThickness = true;
            this.BtnSacar.Click += new System.EventHandler(this.BtnSacar_Click);
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel5.Location = new System.Drawing.Point(46, 57);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(103, 21);
            this.bunifuLabel5.TabIndex = 51;
            this.bunifuLabel5.Text = "Lista permisos:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel4.Location = new System.Drawing.Point(616, 216);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(57, 21);
            this.bunifuLabel4.TabIndex = 50;
            this.bunifuLabel4.Text = "Familias";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel3.Location = new System.Drawing.Point(616, 7);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(64, 21);
            this.bunifuLabel3.TabIndex = 49;
            this.bunifuLabel3.Text = "Permisos";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ListBoxFamilias
            // 
            this.ListBoxFamilias.FormattingEnabled = true;
            this.ListBoxFamilias.Location = new System.Drawing.Point(616, 240);
            this.ListBoxFamilias.Name = "ListBoxFamilias";
            this.ListBoxFamilias.Size = new System.Drawing.Size(191, 173);
            this.ListBoxFamilias.TabIndex = 48;
            this.ListBoxFamilias.SelectedIndexChanged += new System.EventHandler(this.ListBoxFamilias_SelectedIndexChanged);
            // 
            // ListBoxPermisos
            // 
            this.ListBoxPermisos.FormattingEnabled = true;
            this.ListBoxPermisos.Location = new System.Drawing.Point(616, 34);
            this.ListBoxPermisos.Name = "ListBoxPermisos";
            this.ListBoxPermisos.Size = new System.Drawing.Size(191, 160);
            this.ListBoxPermisos.TabIndex = 47;
            this.ListBoxPermisos.SelectedIndexChanged += new System.EventHandler(this.ListBoxPermisos_SelectedIndexChanged);
            // 
            // TxtNombreFamilia
            // 
            this.TxtNombreFamilia.AcceptsReturn = false;
            this.TxtNombreFamilia.AcceptsTab = false;
            this.TxtNombreFamilia.AnimationSpeed = 200;
            this.TxtNombreFamilia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombreFamilia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombreFamilia.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombreFamilia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombreFamilia.BackgroundImage")));
            this.TxtNombreFamilia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombreFamilia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombreFamilia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombreFamilia.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombreFamilia.BorderRadius = 1;
            this.TxtNombreFamilia.BorderThickness = 1;
            this.TxtNombreFamilia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombreFamilia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombreFamilia.DefaultText = "";
            this.TxtNombreFamilia.FillColor = System.Drawing.Color.White;
            this.TxtNombreFamilia.HideSelection = true;
            this.TxtNombreFamilia.IconLeft = null;
            this.TxtNombreFamilia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.IconPadding = 10;
            this.TxtNombreFamilia.IconRight = null;
            this.TxtNombreFamilia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.Lines = new string[0];
            this.TxtNombreFamilia.Location = new System.Drawing.Point(137, 9);
            this.TxtNombreFamilia.MaxLength = 32767;
            this.TxtNombreFamilia.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombreFamilia.Modified = false;
            this.TxtNombreFamilia.Multiline = false;
            this.TxtNombreFamilia.Name = "TxtNombreFamilia";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombreFamilia.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnIdleState = stateProperties4;
            this.TxtNombreFamilia.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNombreFamilia.PasswordChar = '\0';
            this.TxtNombreFamilia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombreFamilia.PlaceholderText = "Enter text";
            this.TxtNombreFamilia.ReadOnly = false;
            this.TxtNombreFamilia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombreFamilia.SelectedText = "";
            this.TxtNombreFamilia.SelectionLength = 0;
            this.TxtNombreFamilia.SelectionStart = 0;
            this.TxtNombreFamilia.ShortcutsEnabled = true;
            this.TxtNombreFamilia.Size = new System.Drawing.Size(203, 21);
            this.TxtNombreFamilia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombreFamilia.TabIndex = 46;
            this.TxtNombreFamilia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombreFamilia.TextMarginBottom = 0;
            this.TxtNombreFamilia.TextMarginLeft = 3;
            this.TxtNombreFamilia.TextMarginTop = 0;
            this.TxtNombreFamilia.TextPlaceholder = "Enter text";
            this.TxtNombreFamilia.UseSystemPasswordChar = false;
            this.TxtNombreFamilia.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel2.Location = new System.Drawing.Point(10, 9);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(115, 21);
            this.bunifuLabel2.TabIndex = 45;
            this.bunifuLabel2.Text = "Nombre Familia:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ListBoxPermisosFamilia
            // 
            this.ListBoxPermisosFamilia.FormattingEnabled = true;
            this.ListBoxPermisosFamilia.Location = new System.Drawing.Point(46, 84);
            this.ListBoxPermisosFamilia.Name = "ListBoxPermisosFamilia";
            this.ListBoxPermisosFamilia.Size = new System.Drawing.Size(243, 290);
            this.ListBoxPermisosFamilia.TabIndex = 44;
            this.ListBoxPermisosFamilia.SelectedIndexChanged += new System.EventHandler(this.ListBoxPermisosFamilia_SelectedIndexChanged);
            // 
            // BtnCancelar
            // 
            this.BtnCancelar.AllowAnimations = true;
            this.BtnCancelar.AllowMouseEffects = true;
            this.BtnCancelar.AllowToggling = false;
            this.BtnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCancelar.AnimationSpeed = 200;
            this.BtnCancelar.AutoGenerateColors = false;
            this.BtnCancelar.AutoRoundBorders = false;
            this.BtnCancelar.AutoSizeLeftIcon = true;
            this.BtnCancelar.AutoSizeRightIcon = true;
            this.BtnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancelar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancelar.BackgroundImage")));
            this.BtnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.ButtonText = "Cancelar";
            this.BtnCancelar.ButtonTextMarginLeft = 0;
            this.BtnCancelar.ColorContrastOnClick = 45;
            this.BtnCancelar.ColorContrastOnHover = 45;
            this.BtnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCancelar.CustomizableEdges = borderEdges4;
            this.BtnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancelar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancelar.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancelar.IconMarginLeft = 11;
            this.BtnCancelar.IconPadding = 10;
            this.BtnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancelar.IconSize = 25;
            this.BtnCancelar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleBorderRadius = 1;
            this.BtnCancelar.IdleBorderThickness = 1;
            this.BtnCancelar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleIconLeftImage = null;
            this.BtnCancelar.IdleIconRightImage = null;
            this.BtnCancelar.IndicateFocus = false;
            this.BtnCancelar.Location = new System.Drawing.Point(262, 441);
            this.BtnCancelar.Name = "BtnCancelar";
            this.BtnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.OnDisabledState.BorderRadius = 1;
            this.BtnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnDisabledState.BorderThickness = 1;
            this.BtnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.OnDisabledState.IconLeftImage = null;
            this.BtnCancelar.OnDisabledState.IconRightImage = null;
            this.BtnCancelar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.BorderRadius = 1;
            this.BtnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.onHoverState.BorderThickness = 1;
            this.BtnCancelar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.onHoverState.IconLeftImage = null;
            this.BtnCancelar.onHoverState.IconRightImage = null;
            this.BtnCancelar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.BorderRadius = 1;
            this.BtnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnIdleState.BorderThickness = 1;
            this.BtnCancelar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.IconLeftImage = null;
            this.BtnCancelar.OnIdleState.IconRightImage = null;
            this.BtnCancelar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCancelar.OnPressedState.BorderRadius = 1;
            this.BtnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnPressedState.BorderThickness = 1;
            this.BtnCancelar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.IconLeftImage = null;
            this.BtnCancelar.OnPressedState.IconRightImage = null;
            this.BtnCancelar.Size = new System.Drawing.Size(150, 39);
            this.BtnCancelar.TabIndex = 43;
            this.BtnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancelar.TextMarginLeft = 0;
            this.BtnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancelar.UseDefaultRadiusAndThickness = true;
            this.BtnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // BtnGuardar
            // 
            this.BtnGuardar.AllowAnimations = true;
            this.BtnGuardar.AllowMouseEffects = true;
            this.BtnGuardar.AllowToggling = false;
            this.BtnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnGuardar.AnimationSpeed = 200;
            this.BtnGuardar.AutoGenerateColors = false;
            this.BtnGuardar.AutoRoundBorders = false;
            this.BtnGuardar.AutoSizeLeftIcon = true;
            this.BtnGuardar.AutoSizeRightIcon = true;
            this.BtnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.BtnGuardar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGuardar.BackgroundImage")));
            this.BtnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.ButtonText = "Guardar";
            this.BtnGuardar.ButtonTextMarginLeft = 0;
            this.BtnGuardar.ColorContrastOnClick = 45;
            this.BtnGuardar.ColorContrastOnHover = 45;
            this.BtnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnGuardar.CustomizableEdges = borderEdges5;
            this.BtnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGuardar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnGuardar.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGuardar.IconMarginLeft = 11;
            this.BtnGuardar.IconPadding = 10;
            this.BtnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGuardar.IconSize = 25;
            this.BtnGuardar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleBorderRadius = 1;
            this.BtnGuardar.IdleBorderThickness = 1;
            this.BtnGuardar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleIconLeftImage = null;
            this.BtnGuardar.IdleIconRightImage = null;
            this.BtnGuardar.IndicateFocus = false;
            this.BtnGuardar.Location = new System.Drawing.Point(494, 441);
            this.BtnGuardar.Name = "BtnGuardar";
            this.BtnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.OnDisabledState.BorderRadius = 1;
            this.BtnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnDisabledState.BorderThickness = 1;
            this.BtnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.OnDisabledState.IconLeftImage = null;
            this.BtnGuardar.OnDisabledState.IconRightImage = null;
            this.BtnGuardar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.BorderRadius = 1;
            this.BtnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.onHoverState.BorderThickness = 1;
            this.BtnGuardar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.onHoverState.IconLeftImage = null;
            this.BtnGuardar.onHoverState.IconRightImage = null;
            this.BtnGuardar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.BorderRadius = 1;
            this.BtnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnIdleState.BorderThickness = 1;
            this.BtnGuardar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnIdleState.IconLeftImage = null;
            this.BtnGuardar.OnIdleState.IconRightImage = null;
            this.BtnGuardar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGuardar.OnPressedState.BorderRadius = 1;
            this.BtnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnPressedState.BorderThickness = 1;
            this.BtnGuardar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnPressedState.IconLeftImage = null;
            this.BtnGuardar.OnPressedState.IconRightImage = null;
            this.BtnGuardar.Size = new System.Drawing.Size(150, 39);
            this.BtnGuardar.TabIndex = 42;
            this.BtnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGuardar.TextMarginLeft = 0;
            this.BtnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGuardar.UseDefaultRadiusAndThickness = true;
            this.BtnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 20.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 16);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(464, 45);
            this.bunifuLabel1.TabIndex = 36;
            this.bunifuLabel1.Text = "Gestión de Familias de Permisos";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnNuevoPerfil
            // 
            this.BtnNuevoPerfil.AllowAnimations = true;
            this.BtnNuevoPerfil.AllowMouseEffects = true;
            this.BtnNuevoPerfil.AllowToggling = false;
            this.BtnNuevoPerfil.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnNuevoPerfil.AnimationSpeed = 200;
            this.BtnNuevoPerfil.AutoGenerateColors = false;
            this.BtnNuevoPerfil.AutoRoundBorders = false;
            this.BtnNuevoPerfil.AutoSizeLeftIcon = true;
            this.BtnNuevoPerfil.AutoSizeRightIcon = true;
            this.BtnNuevoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.BtnNuevoPerfil.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnNuevoPerfil.BackgroundImage")));
            this.BtnNuevoPerfil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.ButtonText = "Nuevo Perfil";
            this.BtnNuevoPerfil.ButtonTextMarginLeft = 0;
            this.BtnNuevoPerfil.ColorContrastOnClick = 45;
            this.BtnNuevoPerfil.ColorContrastOnHover = 45;
            this.BtnNuevoPerfil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnNuevoPerfil.CustomizableEdges = borderEdges6;
            this.BtnNuevoPerfil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnNuevoPerfil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevoPerfil.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevoPerfil.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevoPerfil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnNuevoPerfil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnNuevoPerfil.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnNuevoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevoPerfil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnNuevoPerfil.IconMarginLeft = 11;
            this.BtnNuevoPerfil.IconPadding = 10;
            this.BtnNuevoPerfil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnNuevoPerfil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevoPerfil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnNuevoPerfil.IconSize = 25;
            this.BtnNuevoPerfil.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.IdleBorderRadius = 1;
            this.BtnNuevoPerfil.IdleBorderThickness = 1;
            this.BtnNuevoPerfil.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.IdleIconLeftImage = null;
            this.BtnNuevoPerfil.IdleIconRightImage = null;
            this.BtnNuevoPerfil.IndicateFocus = false;
            this.BtnNuevoPerfil.Location = new System.Drawing.Point(754, 67);
            this.BtnNuevoPerfil.Name = "BtnNuevoPerfil";
            this.BtnNuevoPerfil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevoPerfil.OnDisabledState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnDisabledState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevoPerfil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevoPerfil.OnDisabledState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnDisabledState.IconRightImage = null;
            this.BtnNuevoPerfil.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnNuevoPerfil.onHoverState.BorderRadius = 1;
            this.BtnNuevoPerfil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.onHoverState.BorderThickness = 1;
            this.BtnNuevoPerfil.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnNuevoPerfil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.onHoverState.IconLeftImage = null;
            this.BtnNuevoPerfil.onHoverState.IconRightImage = null;
            this.BtnNuevoPerfil.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnIdleState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnIdleState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.OnIdleState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnIdleState.IconRightImage = null;
            this.BtnNuevoPerfil.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnNuevoPerfil.OnPressedState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnPressedState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.OnPressedState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnPressedState.IconRightImage = null;
            this.BtnNuevoPerfil.Size = new System.Drawing.Size(135, 21);
            this.BtnNuevoPerfil.TabIndex = 43;
            this.BtnNuevoPerfil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnNuevoPerfil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnNuevoPerfil.TextMarginLeft = 0;
            this.BtnNuevoPerfil.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnNuevoPerfil.UseDefaultRadiusAndThickness = true;
            this.BtnNuevoPerfil.Click += new System.EventHandler(this.BtnNuevoPerfil_Click);
            // 
            // BtnEliminar
            // 
            this.BtnEliminar.AllowAnimations = true;
            this.BtnEliminar.AllowMouseEffects = true;
            this.BtnEliminar.AllowToggling = false;
            this.BtnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnEliminar.AnimationSpeed = 200;
            this.BtnEliminar.AutoGenerateColors = false;
            this.BtnEliminar.AutoRoundBorders = false;
            this.BtnEliminar.AutoSizeLeftIcon = true;
            this.BtnEliminar.AutoSizeRightIcon = true;
            this.BtnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.BtnEliminar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEliminar.BackgroundImage")));
            this.BtnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.ButtonText = "Eliminar";
            this.BtnEliminar.ButtonTextMarginLeft = 0;
            this.BtnEliminar.ColorContrastOnClick = 45;
            this.BtnEliminar.ColorContrastOnHover = 45;
            this.BtnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnEliminar.CustomizableEdges = borderEdges7;
            this.BtnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnEliminar.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEliminar.IconMarginLeft = 11;
            this.BtnEliminar.IconPadding = 10;
            this.BtnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEliminar.IconSize = 25;
            this.BtnEliminar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleBorderRadius = 1;
            this.BtnEliminar.IdleBorderThickness = 1;
            this.BtnEliminar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleIconLeftImage = null;
            this.BtnEliminar.IdleIconRightImage = null;
            this.BtnEliminar.IndicateFocus = false;
            this.BtnEliminar.Location = new System.Drawing.Point(540, 67);
            this.BtnEliminar.Name = "BtnEliminar";
            this.BtnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.OnDisabledState.BorderRadius = 1;
            this.BtnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnDisabledState.BorderThickness = 1;
            this.BtnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.OnDisabledState.IconLeftImage = null;
            this.BtnEliminar.OnDisabledState.IconRightImage = null;
            this.BtnEliminar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.BorderRadius = 1;
            this.BtnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.onHoverState.BorderThickness = 1;
            this.BtnEliminar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.onHoverState.IconLeftImage = null;
            this.BtnEliminar.onHoverState.IconRightImage = null;
            this.BtnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.BorderRadius = 1;
            this.BtnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnIdleState.BorderThickness = 1;
            this.BtnEliminar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnIdleState.IconLeftImage = null;
            this.BtnEliminar.OnIdleState.IconRightImage = null;
            this.BtnEliminar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnEliminar.OnPressedState.BorderRadius = 1;
            this.BtnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnPressedState.BorderThickness = 1;
            this.BtnEliminar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnPressedState.IconLeftImage = null;
            this.BtnEliminar.OnPressedState.IconRightImage = null;
            this.BtnEliminar.Size = new System.Drawing.Size(135, 21);
            this.BtnEliminar.TabIndex = 44;
            this.BtnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEliminar.TextMarginLeft = 0;
            this.BtnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEliminar.UseDefaultRadiusAndThickness = true;
            this.BtnEliminar.Click += new System.EventHandler(this.BtnEliminar_Click);
            // 
            // FormGestionFamiliaPermisos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(901, 611);
            this.Controls.Add(this.BtnEliminar);
            this.Controls.Add(this.BtnNuevoPerfil);
            this.Controls.Add(this.BtnNuevaFamilia);
            this.Controls.Add(this.CmbFamilias);
            this.Controls.Add(this.LblUsuariosBloqueados);
            this.Controls.Add(this.PanelData);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormGestionFamiliaPermisos";
            this.Text = "FormGestionFamiliaPermisos";
            this.PanelData.ResumeLayout(false);
            this.PanelData.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnNuevaFamilia;
        private System.Windows.Forms.ComboBox CmbFamilias;
        private Bunifu.UI.WinForms.BunifuLabel LblUsuariosBloqueados;
        private System.Windows.Forms.Panel PanelData;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnAgregar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSacar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.ListBox ListBoxFamilias;
        private System.Windows.Forms.ListBox ListBoxPermisos;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombreFamilia;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.ListBox ListBoxPermisosFamilia;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancelar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnNuevoPerfil;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorNombreFamilia;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEliminar;
    }
}