namespace UI
{
    partial class FormGestionFamiliaPermisos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionFamiliaPermisos));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.BtnNuevaFamilia = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CmbFamilias = new System.Windows.Forms.ComboBox();
            this.LblFamiliasPermisos = new Bunifu.UI.WinForms.BunifuLabel();
            this.PanelData = new System.Windows.Forms.Panel();
            this.LblErrorNombreFamilia = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnAgregarPermiso = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSacarPermiso = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LblListaPermisos = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblFamilias = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblPermisos = new Bunifu.UI.WinForms.BunifuLabel();
            this.ListBoxFamilias = new System.Windows.Forms.ListBox();
            this.ListBoxPermisos = new System.Windows.Forms.ListBox();
            this.TxtNombreFamilia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblNombreFamilia = new Bunifu.UI.WinForms.BunifuLabel();
            this.ListBoxPermisosFamilia = new System.Windows.Forms.ListBox();
            this.BtnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LblGestionFamilias = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnNuevoPerfil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PanelData.SuspendLayout();
            this.SuspendLayout();
            // 
            // BtnNuevaFamilia
            // 
            this.BtnNuevaFamilia.AllowAnimations = true;
            this.BtnNuevaFamilia.AllowMouseEffects = true;
            this.BtnNuevaFamilia.AllowToggling = false;
            this.BtnNuevaFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnNuevaFamilia.AnimationSpeed = 200;
            this.BtnNuevaFamilia.AutoGenerateColors = false;
            this.BtnNuevaFamilia.AutoRoundBorders = false;
            this.BtnNuevaFamilia.AutoSizeLeftIcon = true;
            this.BtnNuevaFamilia.AutoSizeRightIcon = true;
            this.BtnNuevaFamilia.BackColor = System.Drawing.Color.Transparent;
            this.BtnNuevaFamilia.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnNuevaFamilia.BackgroundImage")));
            this.BtnNuevaFamilia.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.ButtonText = "Nueva Familia de Permisos";
            this.BtnNuevaFamilia.ButtonTextMarginLeft = 0;
            this.BtnNuevaFamilia.ColorContrastOnClick = 45;
            this.BtnNuevaFamilia.ColorContrastOnHover = 45;
            this.BtnNuevaFamilia.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnNuevaFamilia.CustomizableEdges = borderEdges1;
            this.BtnNuevaFamilia.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnNuevaFamilia.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevaFamilia.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevaFamilia.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevaFamilia.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnNuevaFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnNuevaFamilia.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnNuevaFamilia.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevaFamilia.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnNuevaFamilia.IconMarginLeft = 11;
            this.BtnNuevaFamilia.IconPadding = 10;
            this.BtnNuevaFamilia.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnNuevaFamilia.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevaFamilia.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnNuevaFamilia.IconSize = 25;
            this.BtnNuevaFamilia.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.IdleBorderRadius = 1;
            this.BtnNuevaFamilia.IdleBorderThickness = 1;
            this.BtnNuevaFamilia.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.IdleIconLeftImage = null;
            this.BtnNuevaFamilia.IdleIconRightImage = null;
            this.BtnNuevaFamilia.IndicateFocus = false;
            this.BtnNuevaFamilia.Location = new System.Drawing.Point(343, 67);
            this.BtnNuevaFamilia.Name = "BtnNuevaFamilia";
            this.BtnNuevaFamilia.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevaFamilia.OnDisabledState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnDisabledState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevaFamilia.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevaFamilia.OnDisabledState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnDisabledState.IconRightImage = null;
            this.BtnNuevaFamilia.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnNuevaFamilia.onHoverState.BorderRadius = 1;
            this.BtnNuevaFamilia.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.onHoverState.BorderThickness = 1;
            this.BtnNuevaFamilia.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnNuevaFamilia.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.onHoverState.IconLeftImage = null;
            this.BtnNuevaFamilia.onHoverState.IconRightImage = null;
            this.BtnNuevaFamilia.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnIdleState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnIdleState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.OnIdleState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnIdleState.IconRightImage = null;
            this.BtnNuevaFamilia.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnNuevaFamilia.OnPressedState.BorderRadius = 1;
            this.BtnNuevaFamilia.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevaFamilia.OnPressedState.BorderThickness = 1;
            this.BtnNuevaFamilia.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevaFamilia.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevaFamilia.OnPressedState.IconLeftImage = null;
            this.BtnNuevaFamilia.OnPressedState.IconRightImage = null;
            this.BtnNuevaFamilia.Size = new System.Drawing.Size(175, 21);
            this.BtnNuevaFamilia.TabIndex = 40;
            this.BtnNuevaFamilia.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnNuevaFamilia.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnNuevaFamilia.TextMarginLeft = 0;
            this.BtnNuevaFamilia.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnNuevaFamilia.UseDefaultRadiusAndThickness = true;
            this.BtnNuevaFamilia.Click += new System.EventHandler(this.BtnNuevaFamilia_Click);
            // 
            // CmbFamilias
            // 
            this.CmbFamilias.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbFamilias.FormattingEnabled = true;
            this.CmbFamilias.Location = new System.Drawing.Point(167, 67);
            this.CmbFamilias.Name = "CmbFamilias";
            this.CmbFamilias.Size = new System.Drawing.Size(158, 21);
            this.CmbFamilias.TabIndex = 39;
            this.CmbFamilias.SelectionChangeCommitted += new System.EventHandler(this.CmbFamilias_SelectionChangeCommitted);
            // 
            // LblFamiliasPermisos
            // 
            this.LblFamiliasPermisos.AllowParentOverrides = false;
            this.LblFamiliasPermisos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblFamiliasPermisos.AutoEllipsis = false;
            this.LblFamiliasPermisos.CursorType = null;
            this.LblFamiliasPermisos.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblFamiliasPermisos.Location = new System.Drawing.Point(12, 67);
            this.LblFamiliasPermisos.Name = "LblFamiliasPermisos";
            this.LblFamiliasPermisos.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblFamiliasPermisos.Size = new System.Drawing.Size(149, 21);
            this.LblFamiliasPermisos.TabIndex = 38;
            this.LblFamiliasPermisos.Text = "Familias de permisos:";
            this.LblFamiliasPermisos.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblFamiliasPermisos.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PanelData
            // 
            this.PanelData.Controls.Add(this.LblErrorNombreFamilia);
            this.PanelData.Controls.Add(this.BtnAgregarPermiso);
            this.PanelData.Controls.Add(this.BtnSacarPermiso);
            this.PanelData.Controls.Add(this.LblListaPermisos);
            this.PanelData.Controls.Add(this.LblFamilias);
            this.PanelData.Controls.Add(this.LblPermisos);
            this.PanelData.Controls.Add(this.ListBoxFamilias);
            this.PanelData.Controls.Add(this.ListBoxPermisos);
            this.PanelData.Controls.Add(this.TxtNombreFamilia);
            this.PanelData.Controls.Add(this.LblNombreFamilia);
            this.PanelData.Controls.Add(this.ListBoxPermisosFamilia);
            this.PanelData.Controls.Add(this.BtnCancelar);
            this.PanelData.Controls.Add(this.BtnGuardar);
            this.PanelData.Location = new System.Drawing.Point(2, 110);
            this.PanelData.Name = "PanelData";
            this.PanelData.Size = new System.Drawing.Size(897, 489);
            this.PanelData.TabIndex = 37;
            // 
            // LblErrorNombreFamilia
            // 
            this.LblErrorNombreFamilia.AllowParentOverrides = false;
            this.LblErrorNombreFamilia.AutoEllipsis = false;
            this.LblErrorNombreFamilia.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblErrorNombreFamilia.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblErrorNombreFamilia.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LblErrorNombreFamilia.ForeColor = System.Drawing.Color.Brown;
            this.LblErrorNombreFamilia.Location = new System.Drawing.Point(346, 13);
            this.LblErrorNombreFamilia.Name = "LblErrorNombreFamilia";
            this.LblErrorNombreFamilia.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblErrorNombreFamilia.Size = new System.Drawing.Size(172, 15);
            this.LblErrorNombreFamilia.TabIndex = 54;
            this.LblErrorNombreFamilia.Text = "Debe ingresar nombre de familia";
            this.LblErrorNombreFamilia.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblErrorNombreFamilia.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.LblErrorNombreFamilia.Visible = false;
            // 
            // BtnAgregarPermiso
            // 
            this.BtnAgregarPermiso.AllowAnimations = true;
            this.BtnAgregarPermiso.AllowMouseEffects = true;
            this.BtnAgregarPermiso.AllowToggling = false;
            this.BtnAgregarPermiso.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnAgregarPermiso.AnimationSpeed = 200;
            this.BtnAgregarPermiso.AutoGenerateColors = false;
            this.BtnAgregarPermiso.AutoRoundBorders = false;
            this.BtnAgregarPermiso.AutoSizeLeftIcon = true;
            this.BtnAgregarPermiso.AutoSizeRightIcon = true;
            this.BtnAgregarPermiso.BackColor = System.Drawing.Color.Transparent;
            this.BtnAgregarPermiso.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAgregarPermiso.BackgroundImage")));
            this.BtnAgregarPermiso.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregarPermiso.ButtonText = "<=";
            this.BtnAgregarPermiso.ButtonTextMarginLeft = 0;
            this.BtnAgregarPermiso.ColorContrastOnClick = 45;
            this.BtnAgregarPermiso.ColorContrastOnHover = 45;
            this.BtnAgregarPermiso.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnAgregarPermiso.CustomizableEdges = borderEdges2;
            this.BtnAgregarPermiso.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAgregarPermiso.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAgregarPermiso.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAgregarPermiso.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAgregarPermiso.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnAgregarPermiso.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnAgregarPermiso.ForeColor = System.Drawing.Color.White;
            this.BtnAgregarPermiso.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAgregarPermiso.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAgregarPermiso.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAgregarPermiso.IconMarginLeft = 11;
            this.BtnAgregarPermiso.IconPadding = 10;
            this.BtnAgregarPermiso.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAgregarPermiso.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAgregarPermiso.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAgregarPermiso.IconSize = 25;
            this.BtnAgregarPermiso.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.IdleBorderRadius = 1;
            this.BtnAgregarPermiso.IdleBorderThickness = 1;
            this.BtnAgregarPermiso.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.IdleIconLeftImage = null;
            this.BtnAgregarPermiso.IdleIconRightImage = null;
            this.BtnAgregarPermiso.IndicateFocus = false;
            this.BtnAgregarPermiso.Location = new System.Drawing.Point(432, 240);
            this.BtnAgregarPermiso.Name = "BtnAgregarPermiso";
            this.BtnAgregarPermiso.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAgregarPermiso.OnDisabledState.BorderRadius = 1;
            this.BtnAgregarPermiso.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregarPermiso.OnDisabledState.BorderThickness = 1;
            this.BtnAgregarPermiso.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAgregarPermiso.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAgregarPermiso.OnDisabledState.IconLeftImage = null;
            this.BtnAgregarPermiso.OnDisabledState.IconRightImage = null;
            this.BtnAgregarPermiso.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnAgregarPermiso.onHoverState.BorderRadius = 1;
            this.BtnAgregarPermiso.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregarPermiso.onHoverState.BorderThickness = 1;
            this.BtnAgregarPermiso.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnAgregarPermiso.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregarPermiso.onHoverState.IconLeftImage = null;
            this.BtnAgregarPermiso.onHoverState.IconRightImage = null;
            this.BtnAgregarPermiso.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.OnIdleState.BorderRadius = 1;
            this.BtnAgregarPermiso.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregarPermiso.OnIdleState.BorderThickness = 1;
            this.BtnAgregarPermiso.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregarPermiso.OnIdleState.IconLeftImage = null;
            this.BtnAgregarPermiso.OnIdleState.IconRightImage = null;
            this.BtnAgregarPermiso.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnAgregarPermiso.OnPressedState.BorderRadius = 1;
            this.BtnAgregarPermiso.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAgregarPermiso.OnPressedState.BorderThickness = 1;
            this.BtnAgregarPermiso.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnAgregarPermiso.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAgregarPermiso.OnPressedState.IconLeftImage = null;
            this.BtnAgregarPermiso.OnPressedState.IconRightImage = null;
            this.BtnAgregarPermiso.Size = new System.Drawing.Size(63, 34);
            this.BtnAgregarPermiso.TabIndex = 53;
            this.BtnAgregarPermiso.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnAgregarPermiso.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAgregarPermiso.TextMarginLeft = 0;
            this.BtnAgregarPermiso.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnAgregarPermiso.UseDefaultRadiusAndThickness = true;
            this.BtnAgregarPermiso.Click += new System.EventHandler(this.BtnAgregar_Click);
            // 
            // BtnSacarPermiso
            // 
            this.BtnSacarPermiso.AllowAnimations = true;
            this.BtnSacarPermiso.AllowMouseEffects = true;
            this.BtnSacarPermiso.AllowToggling = false;
            this.BtnSacarPermiso.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnSacarPermiso.AnimationSpeed = 200;
            this.BtnSacarPermiso.AutoGenerateColors = false;
            this.BtnSacarPermiso.AutoRoundBorders = false;
            this.BtnSacarPermiso.AutoSizeLeftIcon = true;
            this.BtnSacarPermiso.AutoSizeRightIcon = true;
            this.BtnSacarPermiso.BackColor = System.Drawing.Color.Transparent;
            this.BtnSacarPermiso.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSacarPermiso.BackgroundImage")));
            this.BtnSacarPermiso.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacarPermiso.ButtonText = "=>";
            this.BtnSacarPermiso.ButtonTextMarginLeft = 0;
            this.BtnSacarPermiso.ColorContrastOnClick = 45;
            this.BtnSacarPermiso.ColorContrastOnHover = 45;
            this.BtnSacarPermiso.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnSacarPermiso.CustomizableEdges = borderEdges3;
            this.BtnSacarPermiso.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSacarPermiso.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSacarPermiso.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSacarPermiso.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSacarPermiso.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSacarPermiso.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSacarPermiso.ForeColor = System.Drawing.Color.White;
            this.BtnSacarPermiso.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSacarPermiso.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSacarPermiso.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSacarPermiso.IconMarginLeft = 11;
            this.BtnSacarPermiso.IconPadding = 10;
            this.BtnSacarPermiso.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSacarPermiso.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSacarPermiso.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSacarPermiso.IconSize = 25;
            this.BtnSacarPermiso.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.IdleBorderRadius = 1;
            this.BtnSacarPermiso.IdleBorderThickness = 1;
            this.BtnSacarPermiso.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.IdleIconLeftImage = null;
            this.BtnSacarPermiso.IdleIconRightImage = null;
            this.BtnSacarPermiso.IndicateFocus = false;
            this.BtnSacarPermiso.Location = new System.Drawing.Point(432, 186);
            this.BtnSacarPermiso.Name = "BtnSacarPermiso";
            this.BtnSacarPermiso.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSacarPermiso.OnDisabledState.BorderRadius = 1;
            this.BtnSacarPermiso.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacarPermiso.OnDisabledState.BorderThickness = 1;
            this.BtnSacarPermiso.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSacarPermiso.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSacarPermiso.OnDisabledState.IconLeftImage = null;
            this.BtnSacarPermiso.OnDisabledState.IconRightImage = null;
            this.BtnSacarPermiso.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnSacarPermiso.onHoverState.BorderRadius = 1;
            this.BtnSacarPermiso.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacarPermiso.onHoverState.BorderThickness = 1;
            this.BtnSacarPermiso.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnSacarPermiso.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSacarPermiso.onHoverState.IconLeftImage = null;
            this.BtnSacarPermiso.onHoverState.IconRightImage = null;
            this.BtnSacarPermiso.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.OnIdleState.BorderRadius = 1;
            this.BtnSacarPermiso.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacarPermiso.OnIdleState.BorderThickness = 1;
            this.BtnSacarPermiso.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSacarPermiso.OnIdleState.IconLeftImage = null;
            this.BtnSacarPermiso.OnIdleState.IconRightImage = null;
            this.BtnSacarPermiso.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnSacarPermiso.OnPressedState.BorderRadius = 1;
            this.BtnSacarPermiso.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSacarPermiso.OnPressedState.BorderThickness = 1;
            this.BtnSacarPermiso.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnSacarPermiso.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSacarPermiso.OnPressedState.IconLeftImage = null;
            this.BtnSacarPermiso.OnPressedState.IconRightImage = null;
            this.BtnSacarPermiso.Size = new System.Drawing.Size(63, 34);
            this.BtnSacarPermiso.TabIndex = 52;
            this.BtnSacarPermiso.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSacarPermiso.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSacarPermiso.TextMarginLeft = 0;
            this.BtnSacarPermiso.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnSacarPermiso.UseDefaultRadiusAndThickness = true;
            this.BtnSacarPermiso.Click += new System.EventHandler(this.BtnSacar_Click);
            // 
            // LblListaPermisos
            // 
            this.LblListaPermisos.AllowParentOverrides = false;
            this.LblListaPermisos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblListaPermisos.AutoEllipsis = false;
            this.LblListaPermisos.CursorType = null;
            this.LblListaPermisos.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblListaPermisos.Location = new System.Drawing.Point(46, 57);
            this.LblListaPermisos.Name = "LblListaPermisos";
            this.LblListaPermisos.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblListaPermisos.Size = new System.Drawing.Size(103, 21);
            this.LblListaPermisos.TabIndex = 51;
            this.LblListaPermisos.Text = "Lista permisos:";
            this.LblListaPermisos.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblListaPermisos.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblFamilias
            // 
            this.LblFamilias.AllowParentOverrides = false;
            this.LblFamilias.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblFamilias.AutoEllipsis = false;
            this.LblFamilias.CursorType = null;
            this.LblFamilias.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblFamilias.Location = new System.Drawing.Point(616, 216);
            this.LblFamilias.Name = "LblFamilias";
            this.LblFamilias.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblFamilias.Size = new System.Drawing.Size(57, 21);
            this.LblFamilias.TabIndex = 50;
            this.LblFamilias.Text = "Familias";
            this.LblFamilias.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblFamilias.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblPermisos
            // 
            this.LblPermisos.AllowParentOverrides = false;
            this.LblPermisos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblPermisos.AutoEllipsis = false;
            this.LblPermisos.CursorType = null;
            this.LblPermisos.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblPermisos.Location = new System.Drawing.Point(616, 7);
            this.LblPermisos.Name = "LblPermisos";
            this.LblPermisos.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblPermisos.Size = new System.Drawing.Size(64, 21);
            this.LblPermisos.TabIndex = 49;
            this.LblPermisos.Text = "Permisos";
            this.LblPermisos.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblPermisos.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ListBoxFamilias
            // 
            this.ListBoxFamilias.FormattingEnabled = true;
            this.ListBoxFamilias.Location = new System.Drawing.Point(616, 240);
            this.ListBoxFamilias.Name = "ListBoxFamilias";
            this.ListBoxFamilias.Size = new System.Drawing.Size(191, 173);
            this.ListBoxFamilias.TabIndex = 48;
            this.ListBoxFamilias.SelectedIndexChanged += new System.EventHandler(this.ListBoxFamilias_SelectedIndexChanged);
            // 
            // ListBoxPermisos
            // 
            this.ListBoxPermisos.FormattingEnabled = true;
            this.ListBoxPermisos.Location = new System.Drawing.Point(616, 34);
            this.ListBoxPermisos.Name = "ListBoxPermisos";
            this.ListBoxPermisos.Size = new System.Drawing.Size(191, 160);
            this.ListBoxPermisos.TabIndex = 47;
            this.ListBoxPermisos.SelectedIndexChanged += new System.EventHandler(this.ListBoxPermisos_SelectedIndexChanged);
            // 
            // TxtNombreFamilia
            // 
            this.TxtNombreFamilia.AcceptsReturn = false;
            this.TxtNombreFamilia.AcceptsTab = false;
            this.TxtNombreFamilia.AnimationSpeed = 200;
            this.TxtNombreFamilia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombreFamilia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombreFamilia.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombreFamilia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombreFamilia.BackgroundImage")));
            this.TxtNombreFamilia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombreFamilia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombreFamilia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombreFamilia.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombreFamilia.BorderRadius = 1;
            this.TxtNombreFamilia.BorderThickness = 1;
            this.TxtNombreFamilia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombreFamilia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombreFamilia.DefaultText = "";
            this.TxtNombreFamilia.FillColor = System.Drawing.Color.White;
            this.TxtNombreFamilia.HideSelection = true;
            this.TxtNombreFamilia.IconLeft = null;
            this.TxtNombreFamilia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.IconPadding = 10;
            this.TxtNombreFamilia.IconRight = null;
            this.TxtNombreFamilia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombreFamilia.Lines = new string[0];
            this.TxtNombreFamilia.Location = new System.Drawing.Point(137, 9);
            this.TxtNombreFamilia.MaxLength = 32767;
            this.TxtNombreFamilia.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombreFamilia.Modified = false;
            this.TxtNombreFamilia.Multiline = false;
            this.TxtNombreFamilia.Name = "TxtNombreFamilia";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombreFamilia.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombreFamilia.OnIdleState = stateProperties4;
            this.TxtNombreFamilia.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNombreFamilia.PasswordChar = '\0';
            this.TxtNombreFamilia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombreFamilia.PlaceholderText = "Enter text";
            this.TxtNombreFamilia.ReadOnly = false;
            this.TxtNombreFamilia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombreFamilia.SelectedText = "";
            this.TxtNombreFamilia.SelectionLength = 0;
            this.TxtNombreFamilia.SelectionStart = 0;
            this.TxtNombreFamilia.ShortcutsEnabled = true;
            this.TxtNombreFamilia.Size = new System.Drawing.Size(203, 21);
            this.TxtNombreFamilia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombreFamilia.TabIndex = 46;
            this.TxtNombreFamilia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombreFamilia.TextMarginBottom = 0;
            this.TxtNombreFamilia.TextMarginLeft = 3;
            this.TxtNombreFamilia.TextMarginTop = 0;
            this.TxtNombreFamilia.TextPlaceholder = "Enter text";
            this.TxtNombreFamilia.UseSystemPasswordChar = false;
            this.TxtNombreFamilia.WordWrap = true;
            // 
            // LblNombreFamilia
            // 
            this.LblNombreFamilia.AllowParentOverrides = false;
            this.LblNombreFamilia.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LblNombreFamilia.AutoEllipsis = false;
            this.LblNombreFamilia.CursorType = null;
            this.LblNombreFamilia.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.LblNombreFamilia.Location = new System.Drawing.Point(10, 9);
            this.LblNombreFamilia.Name = "LblNombreFamilia";
            this.LblNombreFamilia.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblNombreFamilia.Size = new System.Drawing.Size(115, 21);
            this.LblNombreFamilia.TabIndex = 45;
            this.LblNombreFamilia.Text = "Nombre Familia:";
            this.LblNombreFamilia.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblNombreFamilia.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ListBoxPermisosFamilia
            // 
            this.ListBoxPermisosFamilia.FormattingEnabled = true;
            this.ListBoxPermisosFamilia.Location = new System.Drawing.Point(46, 84);
            this.ListBoxPermisosFamilia.Name = "ListBoxPermisosFamilia";
            this.ListBoxPermisosFamilia.Size = new System.Drawing.Size(243, 290);
            this.ListBoxPermisosFamilia.TabIndex = 44;
            this.ListBoxPermisosFamilia.SelectedIndexChanged += new System.EventHandler(this.ListBoxPermisosFamilia_SelectedIndexChanged);
            // 
            // BtnCancelar
            // 
            this.BtnCancelar.AllowAnimations = true;
            this.BtnCancelar.AllowMouseEffects = true;
            this.BtnCancelar.AllowToggling = false;
            this.BtnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCancelar.AnimationSpeed = 200;
            this.BtnCancelar.AutoGenerateColors = false;
            this.BtnCancelar.AutoRoundBorders = false;
            this.BtnCancelar.AutoSizeLeftIcon = true;
            this.BtnCancelar.AutoSizeRightIcon = true;
            this.BtnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancelar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancelar.BackgroundImage")));
            this.BtnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.ButtonText = "Cancelar";
            this.BtnCancelar.ButtonTextMarginLeft = 0;
            this.BtnCancelar.ColorContrastOnClick = 45;
            this.BtnCancelar.ColorContrastOnHover = 45;
            this.BtnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCancelar.CustomizableEdges = borderEdges4;
            this.BtnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancelar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnCancelar.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancelar.IconMarginLeft = 11;
            this.BtnCancelar.IconPadding = 10;
            this.BtnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancelar.IconSize = 25;
            this.BtnCancelar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleBorderRadius = 1;
            this.BtnCancelar.IdleBorderThickness = 1;
            this.BtnCancelar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.IdleIconLeftImage = null;
            this.BtnCancelar.IdleIconRightImage = null;
            this.BtnCancelar.IndicateFocus = false;
            this.BtnCancelar.Location = new System.Drawing.Point(262, 441);
            this.BtnCancelar.Name = "BtnCancelar";
            this.BtnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.OnDisabledState.BorderRadius = 1;
            this.BtnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnDisabledState.BorderThickness = 1;
            this.BtnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.OnDisabledState.IconLeftImage = null;
            this.BtnCancelar.OnDisabledState.IconRightImage = null;
            this.BtnCancelar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.BorderRadius = 1;
            this.BtnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.onHoverState.BorderThickness = 1;
            this.BtnCancelar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnCancelar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.onHoverState.IconLeftImage = null;
            this.BtnCancelar.onHoverState.IconRightImage = null;
            this.BtnCancelar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.BorderRadius = 1;
            this.BtnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnIdleState.BorderThickness = 1;
            this.BtnCancelar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.IconLeftImage = null;
            this.BtnCancelar.OnIdleState.IconRightImage = null;
            this.BtnCancelar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnCancelar.OnPressedState.BorderRadius = 1;
            this.BtnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnPressedState.BorderThickness = 1;
            this.BtnCancelar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.IconLeftImage = null;
            this.BtnCancelar.OnPressedState.IconRightImage = null;
            this.BtnCancelar.Size = new System.Drawing.Size(150, 39);
            this.BtnCancelar.TabIndex = 43;
            this.BtnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancelar.TextMarginLeft = 0;
            this.BtnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancelar.UseDefaultRadiusAndThickness = true;
            this.BtnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // BtnGuardar
            // 
            this.BtnGuardar.AllowAnimations = true;
            this.BtnGuardar.AllowMouseEffects = true;
            this.BtnGuardar.AllowToggling = false;
            this.BtnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnGuardar.AnimationSpeed = 200;
            this.BtnGuardar.AutoGenerateColors = false;
            this.BtnGuardar.AutoRoundBorders = false;
            this.BtnGuardar.AutoSizeLeftIcon = true;
            this.BtnGuardar.AutoSizeRightIcon = true;
            this.BtnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.BtnGuardar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGuardar.BackgroundImage")));
            this.BtnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.ButtonText = "Guardar";
            this.BtnGuardar.ButtonTextMarginLeft = 0;
            this.BtnGuardar.ColorContrastOnClick = 45;
            this.BtnGuardar.ColorContrastOnHover = 45;
            this.BtnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnGuardar.CustomizableEdges = borderEdges5;
            this.BtnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGuardar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnGuardar.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGuardar.IconMarginLeft = 11;
            this.BtnGuardar.IconPadding = 10;
            this.BtnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGuardar.IconSize = 25;
            this.BtnGuardar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleBorderRadius = 1;
            this.BtnGuardar.IdleBorderThickness = 1;
            this.BtnGuardar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.IdleIconLeftImage = null;
            this.BtnGuardar.IdleIconRightImage = null;
            this.BtnGuardar.IndicateFocus = false;
            this.BtnGuardar.Location = new System.Drawing.Point(494, 441);
            this.BtnGuardar.Name = "BtnGuardar";
            this.BtnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.OnDisabledState.BorderRadius = 1;
            this.BtnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnDisabledState.BorderThickness = 1;
            this.BtnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.OnDisabledState.IconLeftImage = null;
            this.BtnGuardar.OnDisabledState.IconRightImage = null;
            this.BtnGuardar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.BorderRadius = 1;
            this.BtnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.onHoverState.BorderThickness = 1;
            this.BtnGuardar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnGuardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.onHoverState.IconLeftImage = null;
            this.BtnGuardar.onHoverState.IconRightImage = null;
            this.BtnGuardar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.BorderRadius = 1;
            this.BtnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnIdleState.BorderThickness = 1;
            this.BtnGuardar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnIdleState.IconLeftImage = null;
            this.BtnGuardar.OnIdleState.IconRightImage = null;
            this.BtnGuardar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnGuardar.OnPressedState.BorderRadius = 1;
            this.BtnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnPressedState.BorderThickness = 1;
            this.BtnGuardar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnPressedState.IconLeftImage = null;
            this.BtnGuardar.OnPressedState.IconRightImage = null;
            this.BtnGuardar.Size = new System.Drawing.Size(150, 39);
            this.BtnGuardar.TabIndex = 42;
            this.BtnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGuardar.TextMarginLeft = 0;
            this.BtnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGuardar.UseDefaultRadiusAndThickness = true;
            this.BtnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // LblGestionFamilias
            // 
            this.LblGestionFamilias.AllowParentOverrides = false;
            this.LblGestionFamilias.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.LblGestionFamilias.AutoEllipsis = false;
            this.LblGestionFamilias.Cursor = System.Windows.Forms.Cursors.Default;
            this.LblGestionFamilias.CursorType = System.Windows.Forms.Cursors.Default;
            this.LblGestionFamilias.Font = new System.Drawing.Font("Segoe UI", 20.25F);
            this.LblGestionFamilias.Location = new System.Drawing.Point(12, 16);
            this.LblGestionFamilias.Name = "LblGestionFamilias";
            this.LblGestionFamilias.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblGestionFamilias.Size = new System.Drawing.Size(464, 45);
            this.LblGestionFamilias.TabIndex = 36;
            this.LblGestionFamilias.Text = "Gestión de Familias de Permisos";
            this.LblGestionFamilias.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LblGestionFamilias.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnNuevoPerfil
            // 
            this.BtnNuevoPerfil.AllowAnimations = true;
            this.BtnNuevoPerfil.AllowMouseEffects = true;
            this.BtnNuevoPerfil.AllowToggling = false;
            this.BtnNuevoPerfil.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnNuevoPerfil.AnimationSpeed = 200;
            this.BtnNuevoPerfil.AutoGenerateColors = false;
            this.BtnNuevoPerfil.AutoRoundBorders = false;
            this.BtnNuevoPerfil.AutoSizeLeftIcon = true;
            this.BtnNuevoPerfil.AutoSizeRightIcon = true;
            this.BtnNuevoPerfil.BackColor = System.Drawing.Color.Transparent;
            this.BtnNuevoPerfil.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnNuevoPerfil.BackgroundImage")));
            this.BtnNuevoPerfil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.ButtonText = "Nuevo Perfil";
            this.BtnNuevoPerfil.ButtonTextMarginLeft = 0;
            this.BtnNuevoPerfil.ColorContrastOnClick = 45;
            this.BtnNuevoPerfil.ColorContrastOnHover = 45;
            this.BtnNuevoPerfil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnNuevoPerfil.CustomizableEdges = borderEdges6;
            this.BtnNuevoPerfil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnNuevoPerfil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevoPerfil.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevoPerfil.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevoPerfil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnNuevoPerfil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnNuevoPerfil.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnNuevoPerfil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevoPerfil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnNuevoPerfil.IconMarginLeft = 11;
            this.BtnNuevoPerfil.IconPadding = 10;
            this.BtnNuevoPerfil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnNuevoPerfil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnNuevoPerfil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnNuevoPerfil.IconSize = 25;
            this.BtnNuevoPerfil.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.IdleBorderRadius = 1;
            this.BtnNuevoPerfil.IdleBorderThickness = 1;
            this.BtnNuevoPerfil.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.IdleIconLeftImage = null;
            this.BtnNuevoPerfil.IdleIconRightImage = null;
            this.BtnNuevoPerfil.IndicateFocus = false;
            this.BtnNuevoPerfil.Location = new System.Drawing.Point(754, 67);
            this.BtnNuevoPerfil.Name = "BtnNuevoPerfil";
            this.BtnNuevoPerfil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnNuevoPerfil.OnDisabledState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnDisabledState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnNuevoPerfil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnNuevoPerfil.OnDisabledState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnDisabledState.IconRightImage = null;
            this.BtnNuevoPerfil.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnNuevoPerfil.onHoverState.BorderRadius = 1;
            this.BtnNuevoPerfil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.onHoverState.BorderThickness = 1;
            this.BtnNuevoPerfil.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnNuevoPerfil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.onHoverState.IconLeftImage = null;
            this.BtnNuevoPerfil.onHoverState.IconRightImage = null;
            this.BtnNuevoPerfil.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnIdleState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnIdleState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.OnIdleState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnIdleState.IconRightImage = null;
            this.BtnNuevoPerfil.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnNuevoPerfil.OnPressedState.BorderRadius = 1;
            this.BtnNuevoPerfil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnNuevoPerfil.OnPressedState.BorderThickness = 1;
            this.BtnNuevoPerfil.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnNuevoPerfil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnNuevoPerfil.OnPressedState.IconLeftImage = null;
            this.BtnNuevoPerfil.OnPressedState.IconRightImage = null;
            this.BtnNuevoPerfil.Size = new System.Drawing.Size(135, 21);
            this.BtnNuevoPerfil.TabIndex = 43;
            this.BtnNuevoPerfil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnNuevoPerfil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnNuevoPerfil.TextMarginLeft = 0;
            this.BtnNuevoPerfil.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnNuevoPerfil.UseDefaultRadiusAndThickness = true;
            this.BtnNuevoPerfil.Click += new System.EventHandler(this.BtnNuevoPerfil_Click);
            // 
            // BtnEliminar
            // 
            this.BtnEliminar.AllowAnimations = true;
            this.BtnEliminar.AllowMouseEffects = true;
            this.BtnEliminar.AllowToggling = false;
            this.BtnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnEliminar.AnimationSpeed = 200;
            this.BtnEliminar.AutoGenerateColors = false;
            this.BtnEliminar.AutoRoundBorders = false;
            this.BtnEliminar.AutoSizeLeftIcon = true;
            this.BtnEliminar.AutoSizeRightIcon = true;
            this.BtnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.BtnEliminar.BackColor1 = System.Drawing.Color.DimGray;
            this.BtnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEliminar.BackgroundImage")));
            this.BtnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.ButtonText = "Eliminar";
            this.BtnEliminar.ButtonTextMarginLeft = 0;
            this.BtnEliminar.ColorContrastOnClick = 45;
            this.BtnEliminar.ColorContrastOnHover = 45;
            this.BtnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnEliminar.CustomizableEdges = borderEdges7;
            this.BtnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnEliminar.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEliminar.IconMarginLeft = 11;
            this.BtnEliminar.IconPadding = 10;
            this.BtnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEliminar.IconSize = 25;
            this.BtnEliminar.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleBorderRadius = 1;
            this.BtnEliminar.IdleBorderThickness = 1;
            this.BtnEliminar.IdleFillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.IdleIconLeftImage = null;
            this.BtnEliminar.IdleIconRightImage = null;
            this.BtnEliminar.IndicateFocus = false;
            this.BtnEliminar.Location = new System.Drawing.Point(540, 67);
            this.BtnEliminar.Name = "BtnEliminar";
            this.BtnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEliminar.OnDisabledState.BorderRadius = 1;
            this.BtnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnDisabledState.BorderThickness = 1;
            this.BtnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEliminar.OnDisabledState.IconLeftImage = null;
            this.BtnEliminar.OnDisabledState.IconRightImage = null;
            this.BtnEliminar.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.BorderRadius = 1;
            this.BtnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.onHoverState.BorderThickness = 1;
            this.BtnEliminar.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.BtnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.onHoverState.IconLeftImage = null;
            this.BtnEliminar.onHoverState.IconRightImage = null;
            this.BtnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.BorderRadius = 1;
            this.BtnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnIdleState.BorderThickness = 1;
            this.BtnEliminar.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnIdleState.IconLeftImage = null;
            this.BtnEliminar.OnIdleState.IconRightImage = null;
            this.BtnEliminar.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.BtnEliminar.OnPressedState.BorderRadius = 1;
            this.BtnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEliminar.OnPressedState.BorderThickness = 1;
            this.BtnEliminar.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.BtnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnEliminar.OnPressedState.IconLeftImage = null;
            this.BtnEliminar.OnPressedState.IconRightImage = null;
            this.BtnEliminar.Size = new System.Drawing.Size(135, 21);
            this.BtnEliminar.TabIndex = 44;
            this.BtnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEliminar.TextMarginLeft = 0;
            this.BtnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEliminar.UseDefaultRadiusAndThickness = true;
            this.BtnEliminar.Click += new System.EventHandler(this.BtnEliminar_Click);
            // 
            // FormGestionFamiliaPermisos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.LightSteelBlue;
            this.ClientSize = new System.Drawing.Size(901, 611);
            this.Controls.Add(this.BtnEliminar);
            this.Controls.Add(this.BtnNuevoPerfil);
            this.Controls.Add(this.BtnNuevaFamilia);
            this.Controls.Add(this.CmbFamilias);
            this.Controls.Add(this.LblFamiliasPermisos);
            this.Controls.Add(this.PanelData);
            this.Controls.Add(this.LblGestionFamilias);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormGestionFamiliaPermisos";
            this.Text = "FormGestionFamiliaPermisos";
            this.PanelData.ResumeLayout(false);
            this.PanelData.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnNuevaFamilia;
        private System.Windows.Forms.ComboBox CmbFamilias;
        private Bunifu.UI.WinForms.BunifuLabel LblFamiliasPermisos;
        private System.Windows.Forms.Panel PanelData;
        private Bunifu.UI.WinForms.BunifuLabel LblGestionFamilias;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnAgregarPermiso;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSacarPermiso;
        private Bunifu.UI.WinForms.BunifuLabel LblListaPermisos;
        private Bunifu.UI.WinForms.BunifuLabel LblFamilias;
        private Bunifu.UI.WinForms.BunifuLabel LblPermisos;
        private System.Windows.Forms.ListBox ListBoxFamilias;
        private System.Windows.Forms.ListBox ListBoxPermisos;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombreFamilia;
        private Bunifu.UI.WinForms.BunifuLabel LblNombreFamilia;
        private System.Windows.Forms.ListBox ListBoxPermisosFamilia;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancelar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnNuevoPerfil;
        private Bunifu.UI.WinForms.BunifuLabel LblErrorNombreFamilia;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEliminar;
    }
}